NDEV-1925: Remove environmental, rewrite code
neonlabsorg/neon-evm pull request #125
Opened 2023-07-13 13:50 UTC by Deniskore

2023-07-14 13:57 UTC, dk-neon requested changes

2023-07-14 13:58 UTC, dk-neon commented on evm_loader/lib/src/commands/emulate.rs
> +        let (vm_trace, full_trace_data) = evm.get_trace_data();
Oh, now it's fixed.

2023-07-20 12:39 UTC, anton-lisanin requested changes
It's too intrusive in EVM code.
There is also tons of duplicated code.

2023-07-20 15:19 UTC, valiksinev commented
neon-cli generates traces for all commands. So, tracing state-machine is tested by ci-tests of neon-evm, proxy (and uniswap).
The call of precompiled contracts raises error. The event EndStep is called without BeginStep (for derived trace instance).

Also, it is necessary to have only one instance of tracer for evm.

Instead:
let tracer = Rc::new(RefCell::new(Tracer::new()));
we should use the only one tracer instance

2023-07-25 11:57 UTC, Deniskore commented
> It's too intrusive in EVM code. There is also tons of duplicated code.

It was duplicated before with macro, now everything is the same, only without the macro.

2023-08-04 09:29 UTC, Deniskore commented
I was on vacation @andreisilviudragnea took this task for completion in

https://github.com/neonlabsorg/neon-evm/pull/149

2023-08-04 09:29 UTC, closed without merging