NDEV-2555: Clean up tracing code
neonlabsorg/neon-evm pull request #268
Opened 2024-01-31 16:24 UTC by andreisilviudragnea

2024-01-31 17:36 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0030993186318528 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0369701963590896 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005957728436 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0018930411299552 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.006171556680105599 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.7080583600000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.7080583600000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006488373828608 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0030968577938464002 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0031005668704095998 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0031014796389888 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010549575510144 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0068983070524272 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006645109471 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0068053580000448 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.493476579999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0045554582990224 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.003117884841036 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.7114255200000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.7114255200000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.71213988e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0037820248198624003 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.71213988e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.7139658600000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.7139658600000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 4.07094879e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.003878579065556 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.7127521400000005e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013969589034000002 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007597917543999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.7134216400000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

2024-02-01 00:40 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029839657830752 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.035616613405780796 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005739378656 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0018234352425535998 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0059431288164208005 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.6064668800000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.6065914200000002e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006248062223872 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.002982628526864 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029828217837568 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029820799776 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010144124351808 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0066307505367968 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006385597876 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.006539269243660801 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.12228268e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0043770066295648 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0029955075678792 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.60880908e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.6106516400000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.6103683200000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0036366165055568 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.60760688e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.60626788e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.60626788e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.90940287e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0037256088097383996 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.6102000000000002e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013442933554 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007309145143999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.6103439800000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

2024-02-01 03:40 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0028407285260128 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.033896514352809604 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005462154412 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0017358797974943998 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0056625656861872 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.4847148200000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.4847148200000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0005955364480576 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0028437064171936 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0028437064171936 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0028437064171936 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.009672155362752 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0063204690779128 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006087025441 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0062335115716128 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 8.69472037e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0041720902852904 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0028554876158904 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.4841559800000004e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.4841559800000004e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.4841559800000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0034641058309904 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.4838214600000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.4842519800000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.4842519800000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.7263779700000004e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0035512651976776 | 3 | 31 | 3042240 | 1429480 | 46.99 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.4845498200000006e-05 | 22 | 1 | 1578080 | 10000 | 0.63 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0012795908051000003 | 4 | 53 | 3545840 | 515000 | 14.52 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.000695672264 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.4846441200000002e-05 | 23 | 1 | 1707760 | 10000 | 0.59 |

2024-02-01 07:44 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029389860710240003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.035057670490296004 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.000564952586 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0017950971955327999 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0058521909741696 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.5679217600000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.5674722200000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006153717416896 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029384206063456 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.002938933997184 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.002938933997184 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.009996409564416 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0065326926827711995 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006291403363 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.006442810720905601 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 8.987725949999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0043120182440456 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0029512565420904 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.5664886600000004e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.5658557600000004e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.5651691200000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0035767245656928 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.56490954e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.56490954e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.56490954e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.84736212e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0036666626580999996 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.56397998e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013200524084000002 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007180032719999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.5642974000000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

2024-02-01 08:08 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029118481154848004 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0347644826754912 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005602278792 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0017800986212543998 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0058032357228256 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.5464403600000004e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.5464403600000004e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006103308254848001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029143500632128 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029143500632128 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029143500632128 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.009912783033408 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.006478042418225601 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006238778882 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0064001742575328004 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 8.92876341e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0042866106339408 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0029340707815584 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.5527735800000005e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.5524718600000005e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.5526215400000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0035595796850992002 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.5525234000000004e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.5530700000000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.5534685600000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.82997361e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0036499215317967997 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.5535141000000004e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.001315259221 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007150923919999999 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.5539014000000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

2024-02-01 09:04 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029758164216768003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0354885248124576 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005719629476000001 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0018170881690656 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0059229631653856 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.5987582800000005e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.5986982800000004e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006229284925696 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029739926012384 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029748892555392 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029747745786432 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010115905833888 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0066105690986 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006367231941 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.006520461326812801 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.096038909999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0043650441301896 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.002987088845328 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.59864966e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.5987258800000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.5990295e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0036242100680032 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.5988792200000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.59853982e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.59853982e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.89780973e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0037145607018935997 | 3 | 31 | 3042240 | 1429480 | 46.99 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.5990295e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013385001925000002 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007275906791999999 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.5991867600000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

2024-02-01 11:53 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029581600938144 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.035281340817191996 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.000568557022 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.001806564093904 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0058886284907632 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.5837205800000004e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.5855092800000004e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006196709154048 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029570222289088 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029579027689312 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029580628816832 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010064990812704 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.006576364233540801 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006332649162 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0064812056368608005 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.050619409999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0043431673244784 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0029725772120784005 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.58492658e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.5842202e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.5842202e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0036039428909104003 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.5838005200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.5835657e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.58559216e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.87826635e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.003695936121332 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.5844300200000002e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013316916350000004 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007240828615999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.5859087800000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

2024-02-06 09:49 UTC, anton-lisanin requested changes
This is a big no from me. 
Lots of ifdefs and generics make the code unreadable.
It also contains several unrelated changes, have your PRs do one thing instead of everything at the same time. 

And it is not clear why you are doing this. Please update the description and explain why you need these changes from an end-user perspective. What is the user value?

2024-02-13 11:09 UTC, andreisilviudragnea commented
I left in this PR only some duplication removals that I discovered while developing #236.

2024-02-13 11:27 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0288272266264224 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.00046454929840000005 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0014760842797888 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0048122239503712 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.1115877200000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.1115877200000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0005061053447296001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0024166699137856003 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0024272278523856 | 3 | 2 | 2722560 | 1149480 | 42.22 | 
| Swap DAI -> USDC | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1568080 | 10000 | 0.64 | 
| Swap USDC -> DAI | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1568080 | 10000 | 0.64 | 
| Remove liquidity | 2e-05 | 2.1115877200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0029445668437856004 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.16738158e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0030184724139856 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.1115877200000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0010874676758000001 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0005912445616 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.1115877200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.008219988676416 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.005371794696171201 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0005173389914000001 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0052978891259712006 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 7.39055702e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0035463693439856 | 4 | 57 | 4940000 | 1679480 | 34.0 |

2024-02-13 11:36 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0288272266264224 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.00046454929840000005 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0014760842797888 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0048122239503712 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.1115877200000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.1115877200000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0005061053447296001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0024166699137856003 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0024272278523856 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.1115877200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0029445668437856004 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.16738158e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0030184724139856 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.1115877200000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0010874676758000001 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0005912445616 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.1115877200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.008219988676416 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.005371794696171201 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0005173389914000001 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0052978891259712006 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 7.39055702e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0035463693439856 | 4 | 57 | 4940000 | 1679480 | 34.0 |

2024-02-13 16:13 UTC, Deniskore approved these changes
I have no objections.

2024-02-13 18:42 UTC, stanislav-tkach approved these changes

2024-02-14 09:20 UTC, alfiedotwtf approved these changes

2024-02-16 07:13 UTC, andreisilviudragnea commented
For consistency with `EndVM` and `join()` calls, `BeginVM` and `fork()` calls will stay decoupled for now.

2024-02-16 07:13 UTC, closed without merging