NDEV-2841: Extract pda_seeds module
neonlabsorg/neon-evm pull request #379
Opened 2024-04-03 14:31 UTC by andreisilviudragnea

2024-04-03 15:05 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0035817771742111997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0035817462484096 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.012148706155584001 | 4 | 5 | 4845360 | 3976320 | 82.06 | 
| Borrow from lending pool | 0.00519928 | 0.0079425875968088 | 4 | 30 | 3793040 | 2599640 | 68.54 | 
| Repay | 0.00049 | 0.0007485459667 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00512928 | 0.0078357180736224 | 4 | 28 | 7499680 | 2564640 | 34.2 | 
| Withdraw | 7e-05 | 0.0001069342897 | 4 | 5 | 1628080 | 35000 | 2.15 | 
| Liquidation | 0.00341464 | 0.005216493215715201 | 4 | 57 | 4738160 | 1707320 | 36.03 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.007834944757235202 | 16 | 1 | 4154304 | 2564320 | 61.73 | 
| borrow ether cToken | 0.002804 | 0.00428382502 | 13 | 1 | 2601104 | 1402000 | 53.9 | 
| Repay borrow erc20 cToken | 2e-05 | 3.05551e-05 | 17 | 1 | 1362240 | 10000 | 0.73 | 
| Mint erc20 cToken | 2e-05 | 3.05551e-05 | 16 | 1 | 1087592 | 10000 | 0.92 | 
| Mint ether cToken | 2e-05 | 3.05551e-05 | 11 | 1 | 296648 | 10000 | 3.37 | 
| Transfer erc20 cToken | 0.0116432 | 0.017787957016 | 21 | 1 | 6788408 | 5821600 | 85.76 | 
| Add reserves for ether cToken | 2e-05 | 3.05551e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 3.05536936e-05 | 20 | 1 | 1933536 | 10000 | 0.52 | 
| Redeem erc20 cToken | 2e-05 | 3.05536936e-05 | 16 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0071331875226304 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.014235821351660802 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0035818706081152 | 9 | 1 | 199022808 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 3.05536936e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0071331875226304 | 10 | 1 | 199023512 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.014235821351660802 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 3.05536936e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 3.05536936e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0035818706081152 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 3.05536936e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 3.05536936e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0035818706081152 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.06373036292 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0035830788479999996 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0035835124422752 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.03887072 | 0.0594094226662496 | 15 | 1 | 21455896 | 19435360 | 90.58 | 
| Set strategist authority | 2e-05 | 3.0567698600000006e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 3.0570545400000004e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 3.0570545400000004e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00699392 | 0.0106909818561536 | 22 | 1 | 7854000 | 3496960 | 44.52 | 
| Withdraw from vault | 2e-05 | 3.0571740200000003e-05 | 14 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0035827861900352 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.042573147468 | 4 | 28 | 31435120 | 13930320 | 44.31 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0006723530000000001 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.002136371096 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.007135010036 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 3.0558375200000004e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 3.0558375200000004e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0007324231367935999 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.0035824194414463997 | 12 | 1 | 1661680 | 1172320 | 70.55 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0035978825735232 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 3.05599376e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 3.05599376e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 3.05599376e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0043466010447232 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 3.0561501800000004e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 3.05599376e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 3.05599376e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 4.5839906400000004e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.0044535608263232005 | 3 | 31 | 3299760 | 1457320 | 44.16 | 
| Swap SUSD -> LP metapool | 2e-05 | 3.05599376e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0015739473569000002 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0008558875471999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 3.05674124e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0035834252451136 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 3.05669548e-05 | 18 | 1 | 1048720 | 10000 | 0.95 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01664256 | 0.0254357968727808 | 22 | 229 | 12479456 | 8321280 | 66.68 | 
| Metapool: swap 1 | 0.00458 | 0.0069998689686 | 19 | 230 | 4803832 | 2290000 | 47.67 | 
| Metapool: swap 2 | 0.00464 | 0.0070915703088000005 | 19 | 233 | 4836832 | 2320000 | 47.97 | 
| Metapool: withdraw admin fees | 2e-05 | 3.05671686e-05 | 15 | 1 | 549296 | 10000 | 1.82 | 
| Pool: add liquidity | 0.01384464 | 0.0211595959286496 | 26 | 577 | 11162624 | 6922320 | 62.01 | 
| Pool: swap 1 | 0.00542 | 0.0082837119588 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 2 | 0.00542 | 0.0082836901162 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 3 | 0.00542 | 0.008283772933800001 | 19 | 272 | 5265832 | 2710000  [...]

2024-04-03 16:50 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.003603415434736 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.003603415434736 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.012222202863936 | 4 | 5 | 4845360 | 3976320 | 82.06 | 
| Borrow from lending pool | 0.00519928 | 0.007990636430972 | 4 | 30 | 3793040 | 2599640 | 68.54 | 
| Repay | 0.00049 | 0.0007530680884999999 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00512928 | 0.007883166273091201 | 4 | 28 | 7499680 | 2564640 | 34.2 | 
| Withdraw | 7e-05 | 0.0001075826703 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00341464 | 0.005247944133045601 | 4 | 57 | 4967840 | 1707320 | 34.37 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.007882182660105602 | 16 | 1 | 4154304 | 2564320 | 61.73 | 
| borrow ether cToken | 0.002804 | 0.00430945439316 | 13 | 1 | 2601104 | 1402000 | 53.9 | 
| Repay borrow erc20 cToken | 2e-05 | 3.07379058e-05 | 17 | 1 | 1362240 | 10000 | 0.73 | 
| Mint erc20 cToken | 2e-05 | 3.07379058e-05 | 16 | 1 | 1087592 | 10000 | 0.92 | 
| Mint ether cToken | 2e-05 | 3.07379058e-05 | 11 | 1 | 296648 | 10000 | 3.37 | 
| Transfer erc20 cToken | 0.0116432 | 0.017894379240528002 | 21 | 1 | 6788408 | 5821600 | 85.76 | 
| Add reserves for ether cToken | 2e-05 | 3.07379058e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 3.07379058e-05 | 20 | 1 | 1933536 | 10000 | 0.52 | 
| Redeem erc20 cToken | 2e-05 | 3.0738541600000006e-05 | 16 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0071763428761024 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.014319598188 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0036021525647392 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 3.0726703400000006e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0071734677202496 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.0143162558068992 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 3.0726222800000004e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 3.07324998e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.003602153315024 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 3.0726707000000004e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 3.0726707000000004e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0036024050590207995 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.06410582117112 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0036035394661919997 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0036035394661919997 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.03887072 | 0.059741441585616 | 15 | 1 | 21455896 | 19435360 | 90.58 | 
| Set strategist authority | 2e-05 | 3.0738531e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 3.0738531e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 3.0738531e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00699392 | 0.010749141336576 | 22 | 1 | 7854000 | 3496960 | 44.52 | 
| Withdraw from vault | 2e-05 | 3.0738531e-05 | 14 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0036035394661919997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.042819757315991996 | 4 | 28 | 31435120 | 13930320 | 44.31 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.000676247682 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0021487462710239997 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.007176340401384 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 3.0738531e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 3.0731e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0007365606080000001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.0036017494507839995 | 12 | 1 | 1661680 | 1172320 | 70.55 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0036166377285048 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 3.0720200000000004e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 3.07207998e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 3.07230398e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.004370016129955199 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 3.0726707000000004e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 3.07277486e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 3.0726939800000005e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 4.6091637e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.004477864464524001 | 3 | 31 | 3299760 | 1457320 | 44.16 | 
| Swap SUSD -> LP metapool | 2e-05 | 3.0723219200000006e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0015822457888000003 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0008602400128 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 3.0722047000000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0036016070139039996 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 3.0722047000000004e-05 | 18 | 1 | 1048720 | 10000 | 0.95 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01664256 | 0.025564776712780804 | 22 | 229 | 12479456 | 8321280 | 66.68 | 
| Metapool: swap 1 | 0.00458 | 0.007035348762999999 | 19 | 230 | 4803832 | 2290000 | 47.67 | 
| Metapool: swap 2 | 0.00464 | 0.007127514904 | 19 | 233 | 4836832 | 2320000 | 47.97 | 
| Metapool: withdraw admin fees | 2e-05 | 3.0722047000000004e-05 | 15 | 1 | 549296 | 10000 | 1.82 | 
| Pool: add liquidity | 0.01384464 | 0.021265696265539202 | 26 | 577 | 11162624 | 6922320 | 62.01 | 
| Pool: swap 1 | 0.00542 | 0.008325456582 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 2 | 0.00542 | 0.0083259404796 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 3 | 0.00542 | 0 [...]

2024-04-05 01:59 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0035445095199999996 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0035445095199999996 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.01202240352 | 4 | 5 | 4845360 | 3976320 | 82.06 | 
| Borrow from lending pool | 0.00519928 | 0.00786001154 | 4 | 30 | 3793040 | 2599640 | 68.54 | 
| Repay | 0.00049 | 0.0007407574999999999 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00512928 | 0.00775418904 | 4 | 28 | 7499680 | 2564640 | 34.2 | 
| Withdraw | 7e-05 | 0.00010582074999999998 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00341464 | 0.005161825922000001 | 4 | 57 | 4967840 | 1707320 | 34.37 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.007752836872000001 | 16 | 1 | 4154304 | 2564320 | 61.73 | 
| borrow ether cToken | 0.002804 | 0.0042387367000000006 | 13 | 1 | 2601104 | 1402000 | 53.9 | 
| Repay borrow erc20 cToken | 2e-05 | 3.0233500000000005e-05 | 17 | 1 | 1362240 | 10000 | 0.73 | 
| Mint erc20 cToken | 2e-05 | 3.0233500000000005e-05 | 16 | 1 | 1087592 | 10000 | 0.92 | 
| Mint ether cToken | 2e-05 | 3.0233500000000005e-05 | 11 | 1 | 296648 | 10000 | 3.37 | 
| Transfer erc20 cToken | 0.0116432 | 0.017601337594192 | 21 | 1 | 6788408 | 5821600 | 85.76 | 
| Add reserves for ether cToken | 2e-05 | 3.0234536200000005e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 3.0235757000000002e-05 | 20 | 1 | 1933536 | 10000 | 0.52 | 
| Redeem erc20 cToken | 2e-05 | 3.02351504e-05 | 16 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0070587924913967995 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.0140871169825936 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0035444551477984 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 3.0235036200000003e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0070587924913967995 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.014087349946593601 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 3.0235036200000003e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 3.0235036200000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0035445137637984 | 13 | 1 | 199026072 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 3.0235036200000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 3.0235036200000003e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0035445137637984 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.063055772695824 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0035445180075968 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0035445180075968 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.03887072 | 0.0587629516720064 | 15 | 1 | 21455896 | 19435360 | 90.58 | 
| Set strategist authority | 2e-05 | 3.0235072400000004e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 3.0235072400000004e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 3.0235072400000004e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00699392 | 0.0105730712189952 | 22 | 1 | 7854000 | 3496960 | 44.52 | 
| Withdraw from vault | 2e-05 | 3.0235036200000003e-05 | 14 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0035445095199999996 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.042118322519999994 | 4 | 28 | 31435120 | 13930320 | 44.31 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.00066517 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0021135499705248 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0070587924913967995 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 3.0235036200000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 3.0235e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.00072467248 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.0035445095199999996 | 12 | 1 | 1661680 | 1172320 | 70.55 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0035596270199999996 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 3.0235e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 3.0235e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 3.0235e-05 | 23 | 1 | 1707760 | 10000 | 0.59 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.00430038452 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 3.0235e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 3.0235e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 3.0235e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 4.5352499999999996e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.00440620702 | 3 | 31 | 3299760 | 1457320 | 44.16 | 
| Swap SUSD -> LP metapool | 2e-05 | 3.0235e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0015571025 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0008465799999999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 3.0235e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0035445095199999996 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 3.0235e-05 | 18 | 1 | 1048720 | 10000 | 0.95 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01664256 | 0.02515939008 | 22 | 229 | 12479456 | 8321280 | 66.68 | 
| Metapool: swap 1 | 0.00458 | 0.006923815 | 19 | 230 | 4803832 | 2290000 | 47.67 | 
| Metapool: swap 2 | 0.00464 | 0.00701452 | 19 | 233 | 4836832 | 2320000 | 47.97 | 
| Metapool: withdraw admin fees | 2e-05 | 3.0235e-05 | 15 | 1 | 549296 | 10000 | 1.82 | 
| Pool: add liquidity | 0.01384464 | 0.02092963452 | 26 | 577 | 11162624 | 6922320 | 62.01 | 
| Pool: swap 1 | 0.00542 | 0.008193685000000001 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 2 | 0.00542 | 0.008193685000000001 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 3 | 0.00542 | 0.008193685000000001 | 19 | 272 | 5 [...]

2024-04-10 09:14 UTC, Deniskore submitted a review, later dismissed

2024-04-12 06:24 UTC, anton-lisanin requested changes
`pda_seeds.rs` is ugly and not readable.

If you want this information in a one place, create a Notion page.

2024-04-18 20:33 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.002710960692 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 2.3124750000000003e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0027109724152 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.03887072 | 0.044943784115999995 | 15 | 1 | 21455896 | 19435360 | 90.58 | 
| Set strategist authority | 2e-05 | 2.3124750000000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 2.31257506e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 2.31257506e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00699392 | 0.0080865975364608 | 22 | 1 | 4033656 | 3496960 | 86.69 | 
| Withdraw from vault | 2e-05 | 2.3124649800000002e-05 | 14 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0027225584101464 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 2.3125050200000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 2.3124950000000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 2.3124650000000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0032891221400464 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.31249556e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.3124063800000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.3124314200000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 3.46860957e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.0033699371968416 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.3124108600000003e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0011908915929 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0006474750407999999 | 5 | 29 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 2.3124308800000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.005929749928361601 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00324199374476 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 2.3124308800000003e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 2.3124308800000003e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 2.3124308800000003e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.013461931062576 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 2.3124108600000003e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 2.3124108600000003e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 2.3124108600000003e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0053986468901904 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.0107743095433664 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0027109206924415996 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 2.3124509000000003e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.005398740369176 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.0107742629505664 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 2.3124408800000003e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 2.3124408800000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0027109089692416 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 2.3124108600000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 2.3124108600000003e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0027108737761951996 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.048225582415472 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0027108972460415997 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0027108017019616 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0027108251483616 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.009194680849881601 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.0060111978490376 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.0005665182383 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.005930266672137601 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 8.09311769e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0039478690555688 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0170504506395184 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.026899906475416 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 2.3123393800000003e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0027108485947616 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0322130211012144 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005087234636 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0016164736713567998 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0053987135675088 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.3124394200000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 2.31237938e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0005542310897984 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0027108251249151998 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01664256 | 0.0192417896951808 | 22 | 229 | 9164408 | 8321280 | 90.8 | 
| Metapool: swap 1 | 0.00458 | 0.0052952571344 | 19  [...]

2024-05-10 08:58 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0019430834250271998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.6574684400000002e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0019430834250271998 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.03887072 | 0.0322134962087456 | 15 | 1 | 21455896 | 19435360 | 90.58 | 
| Set strategist authority | 2e-05 | 1.65746846e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 1.65746846e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 1.65746846e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00699392 | 0.0057961009058816 | 23 | 1 | 4033656 | 3496960 | 86.69 | 
| Withdraw from vault | 2e-05 | 1.65746846e-05 | 14 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0019513707673271998 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 1.65746846e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.65746846e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.6577827600000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0023579553213952 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.6578233600000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.65786002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.6579000000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 2.48685e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.002416090828 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.6579000000000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0008538185000000001 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0004642119999999999 | 5 | 30 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 1.65790008e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.004251386333145601 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0023243758 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.6579000000000002e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.6562717800000003e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.6562717800000003e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.009643312621488 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.6567907800000003e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.65510128e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.65510128e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0038635297123808 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.0077099316522432 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.001939838021232 | 9 | 1 | 199022808 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.6547001000000002e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.003863129041464 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.007709710616 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.654697e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 1.6546806000000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0019398379039999999 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.6547000000000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.6547000000000003e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.001939815160992 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.03450869484912 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0019398379039999999 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0019398379039999999 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0019398379039999999 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.006579616704000001 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.004301624308 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.0004054015 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.004243709808 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 5.7914054099999994e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0028250972137472 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0122012058800128 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.019248157076888 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.6547000000000003e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0019398379039999999 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.023050500504 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.000364034 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.001156701488 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0038631288079999998 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.6547000000000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.6547000000000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00039659849600000004 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0019398379039999999 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01664256 | 0.013769222016000001 | 22 | 229 | 9164408 | 8321280 | 90.8 | 
| Metapool: swap 1 | 0.00458 | 0.003789263 | 19 | 230 | 2530000 | 2290000 | 90.51 | 
| Metapool: swap 2 | 0.00464 [...]

2024-05-10 13:35 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.001977090951104 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.6866952e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.001977346516864 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.03887072 | 0.0327876128560736 | 15 | 1 | 21455896 | 19435360 | 90.58 | 
| Set strategist authority | 2e-05 | 1.68682458e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 1.6865808600000002e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 1.6865808600000002e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00699392 | 0.0058964294576128 | 22 | 1 | 4033656 | 3496960 | 86.69 | 
| Withdraw from vault | 2e-05 | 1.6858085200000003e-05 | 14 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0019847360867664 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 1.6857370600000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.6862401000000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.68623418e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.00239830460544 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.6861586800000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.6861793400000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.6861793400000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 2.52873738e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.002457320888244 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.6862250200000003e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0008683717202000002 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0004721244304 | 5 | 30 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 1.6861586800000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.00432367943744 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00236387709392 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.6860749600000003e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.68608366e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.6861586800000003e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.009815653870704 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.6860749400000003e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.6860749400000003e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.6860749400000003e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0039364945431504 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.0078561278377008 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0019766778958752 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.6855065e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.00393505089516 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.007852946667688 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.6854421e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 1.68553998e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0019759804358143998 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.6855198600000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.68553998e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0019759922293535997 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.035152273390896 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0019759922293535997 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0019759922293535997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0019759922293535997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.006702133326259201 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.0043817281591616 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.0004129507928 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.0043227351887616 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 5.8990473499999995e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0028777823772352 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0124287905314256 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.01960797614084 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.6855187000000002e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0019759672823839998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0234797733446304 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0003708134584 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0011781789467488 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.003934858800980799 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.6854239000000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.6854239000000002e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.000403962400352 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.001975856146448 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01664256 | 0.014024884190592 | 22 | 229 | 9164408 | 8321280 | 90.8 | 
| Metapool: swap 1 | 0.00458 | 0.0038594284168 | 19 | 230 | 2530000 | 2290000 | 90.51  [...]

2024-05-15 18:45 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0018449573336736 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.021922965079848 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.00034621009280000006 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0011000668330496 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0036739815047936 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.57383638e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.5739427800000004e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00037724260551040003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0018451645998496 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0018449482599168 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0018449482599168 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.006258500154969601 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.0040912048710336 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.00038560985609999995 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.0040365324952992 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 5.50880113e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0026869089183168 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0040356345517664005 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00220641715604 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.5737656e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.5737656e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.57391778e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.009162719748047998 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.57391778e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.5737604600000004e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.5737581e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.011604391723753599 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.018307847614864 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.5737585200000002e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0018530053516775998 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 1.57391818e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.57391778e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.5737604600000004e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0022383909774672 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.5739427800000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.5739427800000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.5739427800000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 2.361075e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.002293894546 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.57405e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0008106254706000001 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0004407284112 | 5 | 30 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 1.5740300400000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0036747934925856 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.0073338464984 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0018452668495999999 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.5740300000000002e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0036747933992 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.0073333935231984 | 12 | 1 | 199023512 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.57393278e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 1.57393278e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0018451528766496 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.57393278e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.57393278e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0018451528766496 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.032824691255536005 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0018451533455776 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01664256 | 0.0130941055855104 | 22 | 229 | 9164408 | 8321280 | 90.8 | 
| Metapool: swap 1 | 0.00458 | 0.0036034722772 | 19 | 230 | 2530000 | 2290000 | 90.51 | 
| Metapool: swap 2 | 0.00464 | 0.0036506793376 | 19 | 233 | 2563000 | 2320000 | 90.52 | 
| Metapool: withdraw admin fees | 2e-05 | 1.57356868e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.01385464 | 0.0109031360255496 | 4 | 578 | 7625552 | 6927320 | 90.84 | 
| Pool: swap 1 | 0.00542 | 0.0042656213 | 19 | 272 | 2992000 | 2710000 | 90.57 | 
| Pool: swap 2 | 0.00542 | 0.0042647812000000005 | 19 | 272 | 2992000 | 2710000 | 90.57 | 
| Pool: swap 3 | 0.00542 | 0.004264781579400001 | 19 | 272 | 2992000 | 2710000 | 90.57 | 
| Pool: withdraw admin fees | 2e-05 | 1.57372014e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.57372014e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01561656 | 0.0122880474947592 | 4 | 39 | 8594608 | 7808280 | 90.85 | 
| Tri pool: swap 1 | 0.00072 | 0.0005665392504 | 20 | 37 | 407000 | 360000 | 88.45 | 
| Tri pool: swap 2 | 0.00072 | 0.0005665392504 | 20 | 37 | 407000 | 360000 | 88.45 | 
| Tri pool: swap 3 | 0.0007 | 0.000550802049 | 20 | 36 | 396000 | 350000 | 88.38 | 
| Tri pool: apply new fee | 2e-05 | 1.57372014e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 |  [...]

2024-05-17 11:09 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0021467014115263998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.025124053424486398 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.493367560000001e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0012800516537408 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.004275426232 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.8314000000000005e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.8313018e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.000438926415424 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.002146986848 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.002146871726176 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.002146871726176 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007281841973376 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.004358310660000001 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 0.0001007325 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0043131266071392 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.411146979999999e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00249464 | 0.0022847864926336 | 5 | 12 | 1752320 | 1247320 | 71.18 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.004697209776793601 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00256812230456 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.83175628e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.83175628e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.83175628e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.010663752941808 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.83175638e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.83176528e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.83176528e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0135062092047232 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.021308279301568 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.8313662e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0021469472235839996 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.8313662e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.8313662e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.83135704e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.002183574786048 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.8313664000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.8313805e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.8313805e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.8318006000000003e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.002184092491392 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.8318789e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.00011907212849999999 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.1575485e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.8315848600000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| DutchAuction started | 2e-05 | 1.8315848600000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0021474152606208 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.8319754400000004e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.83190342e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01236256 | 0.0113263410998528 | 4 | 16 | 9164408 | 6181280 | 67.45 | 
| Metapool: swap 1 | 0.00028 | 0.00025653064639999997 | 4 | 16 | 2530000 | 140000 | 5.53 | 
| Metapool: swap 2 | 0.00028 | 0.00025660807199999995 | 4 | 16 | 2563000 | 140000 | 5.46 | 
| Metapool: withdraw admin fees | 2e-05 | 1.83279942e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.00307464 | 0.002817574883952 | 4 | 39 | 7625552 | 1537320 | 20.16 | 
| Pool: swap 1 | 0.00032 | 0.000293245376 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 2 | 0.00032 | 0.00029323040000000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 3 | 0.00032 | 0.0002931603232 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: withdraw admin fees | 2e-05 | 1.83225202e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.8327915400000002e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01494656 | 0.0136969537479936 | 5 | 9 | 8660608 | 7473280 | 86.29 | 
| Tri pool: swap 1 | 6e-05 | 5.4973308e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 5.4978972599999996e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 5.4978972599999996e-05 | 4 | 5 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.83263242e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.83263242e-05 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.0174800878537408 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.0166127395820032 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.0098015046245344 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.01069664 | 0.0098015046245344 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.00791264 | 0.0072504802958944 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.00512037498148 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.00512038677216 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.00791264 | 0.0072504969915648 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.00512038677216 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.00512038677216 | 26 | 1 | 3359400  [...]

2024-05-17 14:24 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0022647129574335997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.026499991325184 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.794308780000001e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0013501512031904 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.004509125563712 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.9320014000000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.9320014000000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00046306209555200005 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0022649238812479998 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0022649473276479997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0022649692265855996 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007682369847705601 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0045975360595712006 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 0.00010626165440000001 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0045492115728 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.76285071e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0023908029829992003 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0049552031399552 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0027091284826 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.9322500000000003e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.9322218200000002e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.9323000000000005e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.01124907768 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.9323000000000005e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.9320589600000002e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.9320589600000002e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0142463845121728 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.022475871012608 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.93204084e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0022649845605312 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.93205316e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.9320666800000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.9320666800000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0023036417438976 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.9324000000000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.9324000000000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.9324000000000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.9324000000000003e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.002304040598784 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.9324012e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.000125606 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.662923800000001e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.9325847600000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0045120123927648 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.0090046984123296 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0022654995607071997 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.9324859800000003e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0045116590683472 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.0090049966062496 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.9327013200000002e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0022657444114624 | 10 | 1 | 199023128 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.040305537836064 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.0022657438956415997 | 9 | 1 | 199022872 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01236256 | 0.0119465652955264 | 4 | 16 | 9164408 | 6181280 | 67.45 | 
| Metapool: swap 1 | 0.00028 | 0.0002705789016 | 4 | 16 | 2530000 | 140000 | 5.53 | 
| Metapool: swap 2 | 0.00028 | 0.0002705789016 | 4 | 16 | 2563000 | 140000 | 5.46 | 
| Metapool: withdraw admin fees | 2e-05 | 1.93270644e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.00307464 | 0.0029711882643408 | 4 | 39 | 7625552 | 1537320 | 20.16 | 
| Pool: swap 1 | 0.00032 | 0.0003092330304 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 2 | 0.00032 | 0.0003092330304 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 3 | 0.00032 | 0.00030924664000000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: withdraw admin fees | 2e-05 | 1.9327915000000003e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.93278302e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01494656 | 0.0144443298759168 | 5 | 9 | 8660608 | 7473280 | 86.29 | 
| Tri pool: swap 1 | 6e-05 | 5.798389680000001e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 5.7983722800000005e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 5.798389680000001e-05 | 4 | 5 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.9327965600000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.9327965600000003e-05 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.0184352931816576 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.017520548369510402 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.010337232896  [...]

2024-05-20 11:36 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0021014925554208 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.024594948766540798 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.3777796e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0012530943505279998 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0041853408324112 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.79266876e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.79266876e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0004296615754368 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0021014929540096 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0045969105541920005 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0025131566422 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.7923963200000002e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.7923963200000002e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.7923963200000002e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.010427993743695999 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.79068022e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.79068022e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.79068022e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.002098806606176 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.7903018e-05 | 18 | 1 | 130000 | 10000 | 7.69 |

2024-05-22 10:01 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.002126763272912 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.024893157726489597 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.44298334e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0012682876913311999 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0042353783777536 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.8143192800000004e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.8143192800000004e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0004348580823104 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0021267383259424 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0046525170128096 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0025435095216 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.8142008000000002e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.8142008000000002e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.81432778e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.010564924645184 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.81478024e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.81478024e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.8146476600000004e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0133806311575888 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.021111183810568 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.81478024e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0021275031709567997 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.8147262800000004e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.8147262800000004e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.81478024e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.002163107897856 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.8142853000000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.8144923e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.8144923e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.81464086e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0021636325901952 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.8142008000000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.000117923052 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.073456100000001e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.8146912200000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.004236186303272 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.008454227683543999 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.002126823881856 | 9 | 1 | 199022808 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.8146316200000003e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.004235802208299199 | 10 | 1 | 199023512 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.0084554587585056 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.81475652e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 1.8144278e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.002127089998496 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.81446322e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.8144088200000002e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.002126764679696 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.0417104 | 0.037834467336560006 | 18 | 1 | 199022488 | 20855200 | 10.48 | 
| XRT increase allowance | 0.00234464 | 0.002126764679696 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01236256 | 0.011213770966384 | 4 | 16 | 9164408 | 6181280 | 67.45 | 
| Metapool: swap 1 | 0.00028 | 0.00025397408399999995 | 4 | 16 | 2530000 | 140000 | 5.53 | 
| Metapool: swap 2 | 0.00028 | 0.00025397408399999995 | 4 | 16 | 2563000 | 140000 | 5.46 | 
| Metapool: withdraw admin fees | 2e-05 | 1.8141003800000002e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.00307464 | 0.0027888527961816 | 4 | 39 | 7625552 | 1537320 | 20.16 | 
| Pool: swap 1 | 0.00032 | 0.00029028623040000003 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 2 | 0.00032 | 0.00029025606080000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 3 | 0.00032 | 0.0002902604512 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: withdraw admin fees | 2e-05 | 1.81412782e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.8138e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01494656 | 0.013555029135910399 | 5 | 9 | 8660608 | 7473280 | 86.29 | 
| Tri pool: swap 1 | 6e-05 | 5.44139754e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 5.44187802e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 5.44230114e-05 | 4 | 5 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.8139593400000002e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.8139154e-05 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.0173019795351616 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.016442024448 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.009700255471648 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.01069664 | 0.009700255471648 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.00791264 | 0.007175979546112001 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.0050677572 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.0050674817116 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.00791264 | 0.007175577584000001 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.0050674778 | [...]

2024-05-28 09:41 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0018216680479999998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.0213202159921152 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 4.66174608e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0010862489932544 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0036276418424399997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.55391536e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.55391536e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0003724424334848 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0018216860548351998 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0018216860548351998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0018216860548351998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0061788647242752 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0036977591472704 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 8.546725e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0036589928279999995 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 0.00011 | 8.54653448e-05 | 5 | 9 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00251464 | 0.0019537688604352 | 5 | 13 | 1752320 | 1257320 | 71.75 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0039847362359552 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00217858933472 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.55395e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.55391536e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.55395e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.009046273659776 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.55396536e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.55396536e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.55396536e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0114611050467312 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.018076234558152 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.55396536e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0018217446708352 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.5538835e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.5543263400000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.5543263400000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0018528239780352 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.55396536e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.55415376e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.55415376e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.55415376e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0018530486111232 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.55415376e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 0.00011660774399999999 | 5 | 11 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00012 | 9.32861952e-05 | 5 | 9 | 330000 | 60000 | 18.18 | 
| Remove liquidity in Metapool | 2e-05 | 1.55493338e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0036305720491039994 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.007245593212208 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0018231760970016 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.55518638e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0036310176384943996 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.0072464824823888 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.5551727600000002e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 1.5551727600000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0018231247024928 | 13 | 1 | 199026136 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.5550000000000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.5551123200000004e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0018230892749824 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.04176608 | 0.0324725583459904 | 18 | 1 | 199022488 | 20883040 | 10.49 | 
| XRT increase allowance | 0.00234464 | 0.0018229575999999998 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01236256 | 0.0096117220219328 | 4 | 16 | 9164408 | 6181280 | 67.45 | 
| Metapool: swap 1 | 0.00028 | 0.00021769618639999998 | 4 | 16 | 2530000 | 140000 | 5.53 | 
| Metapool: swap 2 | 0.00028 | 0.00021769618639999998 | 4 | 16 | 2563000 | 140000 | 5.46 | 
| Metapool: withdraw admin fees | 2e-05 | 1.55497276e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.00311464 | 0.0024215901786032003 | 4 | 41 | 7625552 | 1557320 | 20.42 | 
| Pool: swap 1 | 0.00032 | 0.00024880000000000003 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 2 | 0.00032 | 0.00024883272640000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 3 | 0.00032 | 0.00024883272640000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: withdraw admin fees | 2e-05 | 1.5550000000000002e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.5552115e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01494656 | 0.011622236700953598 | 5 | 9 | 8660608 | 7473280 | 86.29 | 
| Tri pool: swap 1 | 6e-05 | 4.665e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 8e-05 | 6.220000000000001e-05 | 4 | 6 | 407000 | 40000 | 9.83 | 
| Tri pool: swap 3 | 6e-05 | 4.6645500000000006e-05 | 4 | 5 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.5548716800000002e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.5548203400000003e-05  [...]

2024-05-31 11:18 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0018395089530272 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.021528807389107202 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 4.707355380000001e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0010968765682784 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0036633267214544 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.5691184600000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.5691184600000002e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00037608631249280006 | 12 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0018395089530272 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0018395089530272 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0018395089530272 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.006239317114867201 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0037339370521544003 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 8.63015153e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0036947090906544002 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 0.00011 | 8.63015153e-05 | 5 | 9 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00251464 | 0.0019728840221272 | 5 | 13 | 1752320 | 1257320 | 71.75 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0040237218493472 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0021999040809200002 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.5691184600000002e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.5691184600000002e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.5691184600000002e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.009134780026736001 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.5691184600000002e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.5691184600000002e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.5691184600000002e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0115701774061328 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.018253868868872 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.5691184600000002e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0018395089530272 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.5691184600000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.5691184600000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.5691184600000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0018708913222272002 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.5691184600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.5691184600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.5691184600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.5691184600000002e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0018708913222272002 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.5691184600000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 0.0001176838845 | 5 | 11 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.0001 | 7.8455923e-05 | 5 | 9 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.5691184600000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| DutchAuction started | 2e-05 | 1.5691184600000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0018395089530272 | 13 | 1 | 199026136 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.5691184600000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.5691184600000002e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0018395089530272 | 10 | 1 | 199023128 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.04176608 | 0.0327679635649184 | 18 | 1 | 199022488 | 20883040 | 10.49 | 
| XRT increase allowance | 0.00234464 | 0.0018395089530272 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01236256 | 0.0096991605544288 | 4 | 16 | 9164408 | 6181280 | 67.45 | 
| Metapool: swap 1 | 0.00028 | 0.0002196765844 | 4 | 16 | 2530000 | 140000 | 5.53 | 
| Metapool: swap 2 | 0.00028 | 0.0002196765844 | 4 | 16 | 2563000 | 140000 | 5.46 | 
| Metapool: withdraw admin fees | 2e-05 | 1.5691184600000002e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.00311464 | 0.0024436195601272004 | 4 | 41 | 7625552 | 1557320 | 20.42 | 
| Pool: swap 1 | 0.00032 | 0.00025105895360000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 2 | 0.00032 | 0.00025105895360000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 3 | 0.00032 | 0.00025105895360000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: withdraw admin fees | 2e-05 | 1.5691184600000002e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.5691184600000002e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01494656 | 0.0117264616047488 | 5 | 9 | 8660608 | 7473280 | 86.29 | 
| Tri pool: swap 1 | 6e-05 | 4.707355380000001e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 8e-05 | 6.276473840000001e-05 | 4 | 6 | 407000 | 40000 | 9.83 | 
| Tri pool: swap 3 | 6e-05 | 4.707355380000001e-05 | 4 | 5 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.5691184600000002e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.5691184600000002e-05 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.0149666284599104 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.014223996075161602 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.0083921476419872 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.01069664 | 0.0083921476419872 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.00791264 | 0.006207934745667201 | 26 | 1 [...]

2024-06-12 10:39 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0017682997743551998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.020695406339635198 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 4.5251014200000006e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.001054406700656 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0035214132944144 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.5083639e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.5083639e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.000361524659552 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0017682851672479998 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0017682889655648 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0017682889655648 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.005997750426124801 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00477928 | 0.0036044544524296003 | 5 | 10 | 2644640 | 2389640 | 90.36 | 
| Repay | 0.00011 | 8.29601927e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0035515786250159996 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 0.00011 | 8.29582545e-05 | 5 | 9 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00251464 | 0.0018964171390519998 | 5 | 13 | 1752320 | 1257320 | 71.75 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0038677666767520003 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0021146813238 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.5083319e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.5083319e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.5083113600000002e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.008780755490352 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.50854794e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.50854794e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.5085756600000001e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0111237541726288 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.017549562367912 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.5085600800000001e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0017688231214495998 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.50882278e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.5088885800000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.5089448600000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0017991451354752 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.5089448600000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.5089448600000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.5089448600000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.5089448600000001e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0017990804878847998 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.5090000000000003e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 0.000113175 | 5 | 10 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00012 | 9.054000000000001e-05 | 5 | 9 | 330000 | 60000 | 18.18 | 
| Remove liquidity in Metapool | 2e-05 | 1.5090000000000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.00352297176 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.007030853520000001 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.00176903088 | 9 | 1 | 199022808 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.5090000000000003e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.00352297176 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.007030853520000001 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.5088165800000001e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 1.5088000000000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.001768796416 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.5088000000000002e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.5088000000000002e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0017687826529631998 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.04176608 | 0.031508085585110396 | 18 | 1 | 199022488 | 20883040 | 10.49 | 
| XRT increase allowance | 0.00234464 | 0.0017687469206496 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01236256 | 0.0093260542903584 | 4 | 16 | 9164408 | 6181280 | 67.45 | 
| Metapool: swap 1 | 0.00028 | 0.0002112210324 | 4 | 16 | 2530000 | 140000 | 5.53 | 
| Metapool: swap 2 | 0.00028 | 0.0002112210352 | 4 | 16 | 2563000 | 140000 | 5.46 | 
| Metapool: withdraw admin fees | 2e-05 | 1.5087216800000002e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.00313464 | 0.002364615684 | 4 | 42 | 7625552 | 1567320 | 20.55 | 
| Pool: swap 1 | 0.00032 | 0.00024138554240000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 2 | 0.00032 | 0.00024138554240000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: swap 3 | 0.00032 | 0.00024138554240000004 | 4 | 18 | 2992000 | 160000 | 5.35 | 
| Pool: withdraw admin fees | 2e-05 | 1.5086596400000003e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.5086596400000003e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01494656 | 0.0112744677656192 | 5 | 9 | 8660608 | 7473280 | 86.29 | 
| Tri pool: swap 1 | 6e-05 | 4.52591142e-05 | 4 | 5 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 8e-05 | 6.03372992e-05 | 4 | 6 | 407000 | 40000 | 9.83 | 
| Tri pool: swap 3 | 6e-05 | 4.52529744e-05 | 4 | 5 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.50843248e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool [...]

2024-06-24 09:55 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014294850154976 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014294850154976 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.004848582176217601 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0029016477772952007 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.70650299e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028772604936952006 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.70650299e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015209373289976 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014294850154976 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.2193641800000003e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0031268399540576005 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0017095485803600003 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.2193641800000003e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.2193641800000003e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.2193641800000003e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.007098650510288 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.2193641800000003e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.2193641800000003e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.2193641800000003e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0014294850154976 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.0389264 | 0.023732728908176 | 15 | 1 | 21486520 | 19463200 | 90.58 | 
| Set strategist authority | 2e-05 | 1.2193641800000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 1.2193641800000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 1.2193641800000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00703392 | 0.0042884550464928 | 23 | 4 | 4033656 | 3516960 | 87.19 | 
| Withdraw from vault | 2e-05 | 1.2193641800000003e-05 | 14 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0089912012667824 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.014185107378776 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.2193641800000003e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014294850154976 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0167361635670376 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.65809254e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008523843363872001 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028467763891952 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2193641800000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2193641800000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00029225720666240006 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014294850154976 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0014294850154976 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.2193641800000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2193641800000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2193641800000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014599691199976002 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2193641800000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2193641800000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2193641800000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.2193641800000003e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00239464 | 0.0014599691199976002 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2193641800000003e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.14523135e-05 | 5 | 10 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.70650299e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2193641800000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0028467763891952 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.005681359136590401 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0014294850154976 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.2193641800000003e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0028467763891952 | 10 | 1 | 199023576 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.005681359136590401 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.2193641800000003e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 1.2193641800000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0014294850154976 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 1.2193641800000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 1.2193641800000003e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01234256 | 0.007525037776750401 | 22 | 14 | 9164408 | 6171280 | 67.34 | 
| Metapool: swap 1 | 0.00026 | 0.0001585173434 | 19 | 14 | 2530000 | 130000 | 5.14 | 
| Metapool: swap 2 | 0.00026 | 0.0001585173434 | 19 | 14 | 2563000 | 130000 | 5.07 | 
| Metapool: withdraw admin fees | 2e-05 | 1.2193641800000003e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.0030346 [...]

2024-06-26 08:27 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0030890813677856 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00168890469116 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.2046395800000001e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.2046395800000001e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.007012929778928 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.2046395800000001e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.2046395800000001e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.2046395800000001e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0014122230724256 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.0389264 | 0.023446141073456002 | 15 | 1 | 21486520 | 19463200 | 90.58 | 
| Set strategist authority | 2e-05 | 1.2046395800000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 1.2046395800000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 1.2046395800000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00703392 | 0.0042366692172768 | 23 | 4 | 4033656 | 3516960 | 87.19 | 
| Withdraw from vault | 2e-05 | 1.2046395800000001e-05 | 14 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0088826267782544 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.014013813162056 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.2046395800000001e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1432320 | 1197320 | 83.59 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| XRT transfer | 0.00234464 | 0.0014122230724256 | 10 | 1 | 199023192 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01234256 | 0.007434168147262401 | 22 | 14 | 9164408 | 6171280 | 67.34 | 
| Metapool: swap 1 | 0.00026 | 0.0001566031454 | 19 | 14 | 2530000 | 130000 | 5.14 | 
| Metapool: swap 2 | 0.00026 | 0.0001566031454 | 19 | 14 | 2563000 | 130000 | 5.07 | 
| Metapool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.01385464 | 0.008344923855325601 | 4 | 578 | 7625552 | 6927320 | 90.84 | 
| Pool: swap 1 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 2 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 3 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.2046395800000001e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01495656 | 0.009008632078322401 | 4 | 6 | 8660608 | 7478280 | 86.35 | 
| Tri pool: swap 1 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.2046395800000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: w [...]

2024-07-05 09:54 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0088826267782544 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.014013813162056 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.2046395800000001e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00466928 | 0.0028123997490511997 | 10 | 1 | 199023640 | 2334640 | 1.17 | 
| PublicAmbix appendSource | 0.00931856 | 0.0056127531023024 | 12 | 1 | 199023640 | 4659280 | 2.34 | 
| XRT approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 199022872 | 1172320 | 0.59 | 
| PublicAmbix run | 2e-05 | 1.2046395800000001e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00466928 | 0.0028123997490511997 | 10 | 1 | 199023512 | 2334640 | 1.17 | 
| KycAmbix appendSource | 0.00931856 | 0.0056127531023024 | 12 | 1 | 199023576 | 4659280 | 2.34 | 
| KycAmbix run | 2e-05 | 1.2046395800000001e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0014122230724256 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.04176608 | 0.0251565365347232 | 18 | 1 | 199022488 | 20883040 | 10.49 | 
| XRT increase allowance | 0.00234464 | 0.0014122230724256 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01234256 | 0.007434168147262401 | 22 | 14 | 9164408 | 6171280 | 67.34 | 
| Metapool: swap 1 | 0.00026 | 0.0001566031454 | 19 | 14 | 2530000 | 130000 | 5.14 | 
| Metapool: swap 2 | 0.00026 | 0.0001566031454 | 19 | 14 | 2563000 | 130000 | 5.07 | 
| Metapool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.01385464 | 0.008344923855325601 | 4 | 578 | 7625552 | 6927320 | 90.84 | 
| Pool: swap 1 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 2 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 3 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.2046395800000001e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01495656 | 0.009008632078322401 | 4 | 6 | 8660608 | 7478280 | 86.35 | 
| Tri pool: swap 1 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.2046395800000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.0114901414275392 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.010920009607116801 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.0064427979585056005 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.01069664 | 0.0064427979585056005 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.00791264 | 0.0047659396631456 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.0033657629865200002 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.0033657629865200002 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.00791264 | 0.0047659396631456 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.0033657629865200002 | 26 | 1 | 3359400 | 279400 [...]

2024-07-05 10:37 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |  421964 |      0     |      0.504 |    0.00148292  |         0     |
| getSlot                           |  294588 |      0     |      3.55  |    0.00122017  |         0     |
| getTransaction                    |  238820 |      0     |      0.162 |    0.00421536  |         0.002 |
| sendTransaction                   |  206283 |      0     |      2.365 |    0.00805985  |         0.002 |
| getBlocks                         |   84662 |      0     |      0.206 |    0.000611006 |         0     |
| getMultipleAccounts               |   74837 |      0     |      0.409 |    0.00235445  |         0.001 |
| getBlockTime                      |   50491 |      0     |      0.255 |    0.000649066 |         0     |
| getBlock                          |   42429 |      0     |      0.263 |    0.00103349  |         0.001 |
| getLatestBlockhash                |   35858 |      0     |      3.551 |    0.0033566   |         0.001 |
| getBalance                        |   15299 |      0     |      0.153 |    0.00144657  |         0     |
| getSignatureStatuses              |    1344 |      0     |      0.073 |    0.00135342  |         0     |
| getVersion                        |     693 |      0     |      0.083 |    0.00154257  |         0     |
| isBlockhashValid                  |     654 |      0     |      0.018 |    0.000539755 |         0     |
| getSignaturesForAddress           |     171 |      0     |      0.017 |    0.00231579  |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00053125  |         0.001 |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000434783 |         0     |
| getHealth                         |       3 |      0     |      0.004 |    0.00166667  |         0.001 |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0.052 |      0.052 |    0.052       |         0.052 |

</details>

2024-07-05 12:04 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0088826267782544 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.014013813162056 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.2046395800000001e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| XRT transfer | 0.00234464 | 0.0014122230724256 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.04176608 | 0.0251565365347232 | 18 | 1 | 199022488 | 20883040 | 10.49 | 
| XRT increase allowance | 0.00234464 | 0.0014122230724256 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01234256 | 0.007434168147262401 | 22 | 14 | 9164408 | 6171280 | 67.34 | 
| Metapool: swap 1 | 0.00026 | 0.0001566031454 | 19 | 14 | 2530000 | 130000 | 5.14 | 
| Metapool: swap 2 | 0.00026 | 0.0001566031454 | 19 | 14 | 2563000 | 130000 | 5.07 | 
| Metapool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.01385464 | 0.008344923855325601 | 4 | 578 | 7625552 | 6927320 | 90.84 | 
| Pool: swap 1 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 2 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 3 | 0.0003 | 0.000180695937 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.2046395800000001e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01495656 | 0.009008632078322401 | 4 | 6 | 8660608 | 7478280 | 86.35 | 
| Tri pool: swap 1 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 3.6139187400000005e-05 | 20 | 4 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.2046395800000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.2046395800000001e-05 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.0114901414275392 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.010920009607116801 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.0064427979585056005 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.01069664 | 0.0064427979585056005 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.00791264 | 0.0047659396631456 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.0033657629865200002 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.0033657629865200002 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.00791264 | 0.0047659396631456 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.0033657629865200002 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.0033657629865200002 | 26 | 1 | 3359400 | 2794000 | 83.17 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0030890813677856 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00168890469116 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.2046395800000001e-05 | 16 | 1 | 77000 | 10000 | 12.99 |  [...]

2024-07-05 12:48 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |  420622 |      0     |      0.446 |    0.00147229  |         0     |
| getSlot                           |  287705 |      0     |      0.392 |    0.00116519  |         0     |
| getTransaction                    |  265180 |      0     |      0.403 |    0.00366968  |         0.002 |
| sendTransaction                   |  232604 |      0     |      0.432 |    0.00705753  |         0.002 |
| getBlocks                         |   83182 |      0     |      0.302 |    0.000643721 |         0     |
| getMultipleAccounts               |   72269 |      0     |      0.472 |    0.00222293  |         0.001 |
| getBlockTime                      |   49262 |      0     |      0.395 |    0.000699586 |         0     |
| getBlock                          |   41700 |      0     |      0.183 |    0.00108175  |         0.001 |
| getLatestBlockhash                |   35814 |      0     |      3.86  |    0.00281694  |         0.001 |
| getBalance                        |   15288 |      0     |      0.196 |    0.00148221  |         0     |
| getSignatureStatuses              |    1315 |      0     |      0.118 |    0.00147681  |         0.001 |
| getVersion                        |     679 |      0     |      0.023 |    0.00134904  |         0     |
| isBlockhashValid                  |     639 |      0     |      0.09  |    0.00070266  |         0     |
| getSignaturesForAddress           |     167 |      0     |      0.008 |    0.00176048  |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00046875  |         0     |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000478261 |         0     |
| getHealth                         |       3 |      0     |      0.001 |    0.000666667 |         0.001 |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000666667 |         0.001 |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.002 |      0.002 |    0.002       |         0.002 |

</details>

2024-07-11 17:29 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.0061548454997696 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.009710286948704001 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 8.347047200000002e-06 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0021404500075904004 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.0011702560174400001 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 8.347047200000002e-06 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 8.347047200000002e-06 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.004859316997952 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 8.347047200000002e-06 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 8.347047200000002e-06 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 8.347047200000002e-06 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| DutchAuction started | 2e-05 | 8.347047200000002e-06 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00234464 | 0.0009785410373504 | 13 | 1 | 199026200 | 1172320 | 0.59 | 
| DutchAuction update stage | 2e-05 | 8.347047200000002e-06 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00234464 | 0.0009785410373504 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.04176608 | 0.0174311720559488 | 18 | 1 | 199022488 | 20883040 | 10.49 | 
| XRT increase allowance | 0.00234464 | 0.0009785410373504 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0009785410373504 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.0389264 | 0.016246024906304002 | 15 | 1 | 21486520 | 19463200 | 90.58 | 
| Set strategist authority | 2e-05 | 8.347047200000002e-06 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 8.347047200000002e-06 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 8.347047200000002e-06 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00703392 | 0.0029356231120512004 | 23 | 4 | 4033656 | 3516960 | 87.19 | 
| Withdraw from vault | 2e-05 | 8.347047200000002e-06 | 14 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01234256 | 0.0051511965444416006 | 22 | 14 | 9164408 | 6171280 | 67.34 | 
| Metapool: swap 1 | 0.00026 | 0.0001085116136 | 19 | 14 | 2530000 | 130000 | 5.14 | 
| Metapool: swap 2 | 0.00026 | 0.0001085116136 | 19 | 14 | 2563000 | 130000 | 5.07 | 
| Metapool: withdraw admin fees | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.01385464 | 0.0057822667009504005 | 4 | 578 | 7625552 | 6927320 | 90.84 | 
| Pool: swap 1 | 0.0003 | 0.000125205708 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 2 | 0.0003 | 0.000125205708 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 3 | 0.0003 | 0.000125205708 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: withdraw admin fees | 2e-05 | 8.347047200000002e-06 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 8.347047200000002e-06 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01495656 | 0.006242155613481601 | 4 | 6 | 8660608 | 7478280 | 86.35 | 
| Tri pool: swap 1 | 6e-05 | 2.50411416e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 2.50411416e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 2.50411416e-05 | 20 | 4 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 8.347047200000002e-06 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 8.347047200000002e-06 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.007961613948492801 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.007566564898611201 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.004464267948070401 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.01069664 | 0.004464267948070401 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.00791264 | 0.0033023589778304004 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.00233216498768 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.00233216498768 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.00791264 | 0.0033023589778304004 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.00233216498768 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.00233216498768 | 26 | 1 | 3359400 | 2794000 | 83.17 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.004759 [...]

2024-07-11 18:18 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |  423340 |          0 |      0.587 |    0.00238436  |         0.001 |
| getSlot                           |  313621 |          0 |      0.447 |    0.00171742  |         0.001 |
| getTransaction                    |  240673 |          0 |      0.826 |    0.00571397  |         0.002 |
| sendTransaction                   |  207928 |          0 |      0.459 |    0.00984283  |         0.004 |
| getBlocks                         |   95931 |          0 |      0.397 |    0.00103927  |         0.001 |
| getMultipleAccounts               |   75197 |          0 |      0.515 |    0.00332419  |         0.001 |
| getBlock                          |   53235 |          0 |      0.324 |    0.00166441  |         0.001 |
| getBlockTime                      |   50782 |          0 |      0.221 |    0.00112526  |         0     |
| getLatestBlockhash                |   35909 |          0 |      0.384 |    0.00368337  |         0.001 |
| getBalance                        |   15322 |          0 |      0.208 |    0.00227281  |         0.001 |
| getSignatureStatuses              |    1341 |          0 |      0.226 |    0.00234228  |         0.001 |
| getVersion                        |     693 |          0 |      0.041 |    0.00246898  |         0.001 |
| isBlockhashValid                  |     651 |          0 |      0.031 |    0.00125499  |         0     |
| getSignaturesForAddress           |     167 |          0 |      0.038 |    0.008       |         0.003 |
| requestAirdrop                    |      32 |          0 |      0.002 |    0.00103125  |         0.001 |
| simulateTransaction               |      23 |          0 |      0.001 |    0.000521739 |         0.001 |
| getHealth                         |       4 |          0 |      0.001 |    0.00075     |         0.001 |
| getTokenAccountBalance            |       3 |          0 |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       3 |          0 |      0.001 |    0.000666667 |         0.001 |
| getMinimumBalanceForRentExemption |       1 |          0 |      0     |    0           |         0     |
| getClusterNodes                   |       1 |          0 |      0     |    0           |         0     |

</details>

2024-07-23 14:21 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Pancake Lottery" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Cost to start the lottery | 0.01474736 | 0.008406290147199999 | 9 | 1 | 7413680 | 7373680 | 99.46 | 
| Cost to buy a stand-alone ticket | 0.0232664 | 0.013262313328 | 23 | 1 | 11693200 | 11633200 | 99.49 | 
| Cost to do injection | 2e-05 | 1.13994e-05 | 13 | 1 | 50000 | 10000 | 20.0 | 

Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0029234273728 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00159833608 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.14004e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.14004e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.14004e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.006639069072 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.14042e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.14042e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.14042e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0013369371744 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.14014e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| XRT transfer | 0.00234464 | 0.0013367027103999998 | 10 | 1 | 199023192 | 1172320 | 0.59 | 
| Factory create lighthouse | 0.04176608 | 0.0238112598688 | 18 | 1 | 199022488 | 20883040 | 10.49 | 
| XRT increase allowance | 0.00234464 | 0.0013369371744 | 9 | 1 | 199022936 | 1172320 | 0.59 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0013426392744 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.14014e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.1402000000000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.14014e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.001365184264 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.14014e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.1402000000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.1403600000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.7103000000000002e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.001365184264 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.1402000000000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 8.5515e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.2711e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.1403200000000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00234464 | 0.0013368199424 | 13 | 1 | 1322552 | 1172320 | 88.64 | 
| Clone strategy | 0.0389264 | 0.022195444015999998 | 15 | 1 | 21486520 | 19463200 | 90.58 | 
| Set strategist authority | 2e-05 | 1.14038e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 1.1403200000000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 1.1403200000000001e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00703392 | 0.0040106708448 | 23 | 4 | 4033656 | 3516960 | 87.19 | 
| Withdraw from vault | 2e-05 | 1.14038e-05 | 14 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01234256 | 0.0070376042864 | 22 | 14 | 9164408 | 6171280 | 67.34 | 
| Metapool: swap 1 | 0.00026 | 0.00014824159999999998 | 19 | 14 | 2530000 | 130000 | 5.14 | 
| Metapool: swap 2 | 0.00026 | 0.00014824939999999998 | 19 | 14 | 2563000 | 130000 | 5.07 | 
| Metapool: withdraw admin fees | 2e-05 | 1.14038e-05 | 15 | 1 | 44000 | 10000 | 22.73 | 
| Pool: add liquidity | 0.01385464 | 0.007899777181599999 | 4 | 578 | 7625552 | 6927320 | 90.84 | 
| Pool: swap 1 | 0.0003 | 0.00017105099999999997 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 2 | 0.0003 | 0.00017105699999999999 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: swap 3 | 0.0003 | 0.00017105699999999999 | 19 | 16 | 2992000 | 150000 | 5.01 | 
| Pool: withdraw admin fees | 2e-05 | 1.1402600000000002e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 1.1402600000000002e-05 | 10 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: add liquidity | 0.01495656 | 0.008527183552800001 | 4 | 6 | 8660608 | 7478280 | 86.35 | 
| Tri pool: swap 1 | 6e-05 | 3.42102e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 2 | 6e-05 | 3.42078e-05 | 20 | 4 | 407000 | 30000 | 7.37 | 
| Tri pool: swap 3 | 6e-05 | 3.42078e-05 | 20 | 4 | 396000 | 30000 | 7.58 | 
| Tri pool: apply new fee | 2e-05 | 1.1402600000000002e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 1.14034e-05 | 18 | 1 | 55000 | 10000 | 18.18 | 
| gauge v3: deposit | 0.01907648 | 0.0108772181312 | 28 | 1 | 10646064 | 9538240 | 89.59 | 
| gauge controller: vote | 0.01812992 | 0.0103364112896 | 26 | 1 | 10257456 | 9064960 | 88.37 | 
| gauge controller: vote | 0.01069664 | 0.0060984753632 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.01069664 | 0.0060991171616 | 26 | 1 | 6169152 | 5348320 | 86.69 | 
| gauge controller: vote | 0.00791264 | 0.0045117082016 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.00745328 | 0.0042497857232 | 27 | 1 | 4385304 | 3726640 | 84.98 | 
| gauge controller: vote | 0.005588 | 0.00318622172 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.00791264 | 0.0045117082016 | 26 | 1 | 4637952 | 3956320 | 85.3 | 
| gauge controller: vote | 0.005588 | 0.00318622172 | 26 | 1 | 3359400 | 2794000 | 83.17 | 
| gauge controller: vote | 0.005588 | 0.00318622172 | 26 | 1 | 3359400 | 2794000 | 83.17 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0013368902816 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0013368902816 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00796264 | 0.0045402177015999995 | 5 | 5 | 4156320 | 3981320 | 95.79 | 
| Borrow from lending pool | 0.00475928 | 0.0027136938632 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.27209e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00475928 | 0.0027139318272 | 4 | 5 | 2634640 | 2379640 | 90.32 | 
| Withdraw | 0.00011 | 6.27264e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0014225435135999998 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| -- [...]

2024-07-23 15:10 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |  423018 |      0     |      0.467 |    0.00261603  |        0.001  |
| getSlot                           |  293449 |      0     |      0.69  |    0.0019633   |        0.001  |
| getTransaction                    |  227714 |      0     |      0.34  |    0.00606004  |        0.003  |
| sendTransaction                   |  195068 |      0     |      0.407 |    0.00993449  |        0.004  |
| getBlocks                         |   90123 |      0     |      0.342 |    0.00136964  |        0.001  |
| getMultipleAccounts               |   76912 |      0     |      0.366 |    0.00330878  |        0.001  |
| getBlockTime                      |   51385 |      0     |      0.285 |    0.00134022  |        0.001  |
| getBlock                          |   45274 |      0     |      0.202 |    0.0019001   |        0.001  |
| getLatestBlockhash                |   35828 |      0     |      2.26  |    0.00370663  |        0.001  |
| getBalance                        |   15293 |      0     |      0.214 |    0.00267645  |        0.001  |
| getSignatureStatuses              |    1327 |      0     |      0.153 |    0.00273399  |        0.001  |
| getVersion                        |     685 |      0     |      0.152 |    0.00271387  |        0.001  |
| isBlockhashValid                  |     645 |      0     |      0.025 |    0.00107752  |        0.001  |
| getSignaturesForAddress           |     176 |      0     |      0.032 |    0.0058125   |        0.004  |
| requestAirdrop                    |      32 |      0.001 |      0.002 |    0.001125    |        0.001  |
| simulateTransaction               |      23 |      0     |      0.002 |    0.00073913  |        0.001  |
| getHealth                         |       3 |      0.001 |      0.001 |    0.001       |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0.03  |      0.03  |    0.03        |        0.03   |

</details>

2024-07-31 08:26 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00512864 | 0.0027898263008 | 16 | 1 | 2875752 | 2564320 | 89.17 | 
| borrow ether cToken | 0.002804 | 0.00152531992 | 13 | 1 | 1575200 | 1402000 | 89.0 | 
| Repay borrow erc20 cToken | 2e-05 | 1.08794e-05 | 17 | 1 | 99000 | 10000 | 10.1 | 
| Mint erc20 cToken | 2e-05 | 1.08794e-05 | 16 | 1 | 77000 | 10000 | 12.99 | 
| Mint ether cToken | 2e-05 | 1.0879000000000002e-05 | 11 | 1 | 44000 | 10000 | 22.73 | 
| Transfer erc20 cToken | 0.0116432 | 0.006333784368 | 21 | 1 | 6535760 | 5821600 | 89.07 | 
| Add reserves for ether cToken | 2e-05 | 1.08798e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 1.08794e-05 | 20 | 1 | 165000 | 10000 | 6.06 | 
| Redeem erc20 cToken | 2e-05 | 1.08794e-05 | 16 | 1 | 66000 | 10000 | 15.15 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0012754607135999998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 1.08798e-05 | 18 | 1 | 130000 | 10000 | 7.69 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0012754607135999998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02747064 | 0.0149410063896 | 4 | 7 | 14000320 | 13735320 | 98.11 | 
| NonfungiblePositionManager - Increase liquidity  | 8e-05 | 4.3508e-05 | 23 | 6 | 230000 | 40000 | 17.39 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0007603458079999999 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.002539621392 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.08776e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.08776e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.000260699936 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0012751324639999999 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-10-18 08:43 UTC, closed without merging