NDEV-2845: Disable sysvar and feature account retrieval for ClickHouse Rpc
neonlabsorg/neon-evm pull request #384
Opened 2024-04-08 12:19 UTC by andreisilviudragnea

2024-04-08 13:20 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0032516950739263995 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0032516950739263995 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0110292242360064 | 4 | 5 | 4845360 | 3976320 | 82.06 | 
| Borrow from lending pool | 0.00519928 | 0.007210690410452799 | 4 | 30 | 3793040 | 2599640 | 68.54 | 
| Repay | 0.00049 | 0.0006796540247 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00512928 | 0.0071143336210752 | 4 | 28 | 7499680 | 2564640 | 34.2 | 
| Withdraw | 7e-05 | 9.709779449999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00341464 | 0.004736485900164 | 4 | 57 | 4967840 | 1707320 | 34.37 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0032524846079999997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.038648279808 | 4 | 28 | 31435120 | 13930320 | 44.31 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.000610368 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0019393732634816 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.006477080561705599 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.77433804e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.7741227000000002e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006647695787712001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.0032515131533088 | 12 | 1 | 1661680 | 1172320 | 70.55 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0032653891806096 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 2.77328714e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.7737849e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.7742311600000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0039460717786736 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.7743909800000005e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.7737893000000005e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.7737893000000005e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 4.1603670900000005e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.0040421172154824 | 3 | 31 | 3299760 | 1457320 | 44.16 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.7736648200000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0014284373823 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007766261495999999 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.7736648200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

2024-04-09 10:02 UTC, stanislav-tkach approved these changes, later dismissed

2024-04-12 06:22 UTC, anton-lisanin requested changes

2024-04-12 06:22 UTC, anton-lisanin commented on evm_loader/lib/src/rpc/db_call_client.rs
> +        false
Features should be supported by the ClickHouse DB in the future.
I don't want to remember to change the neon-api code when this happens.

2024-04-18 21:01 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0027139730159640003 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 2.3052127000000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 2.3052127000000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 2.3052127000000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0032787501274640003 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.30510768e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.30510768e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.30510768e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 3.45781155e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.0033595818889712004 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.3053151600000004e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0011872373074000003 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0006454882448 | 5 | 30 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 2.30532016e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0027025729299711997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0027025729299711997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0091666906586112 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.0059930025007424 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.0005648240143 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.0059128544592000004 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 8.06939357e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0039362962942664 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0027028318485664 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0321169241817264 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005072190244000001 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0016116720494816 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0053826305127055996 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.3055505400000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 2.3055505400000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0005525943534272 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0027028430090527997 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-05-09 13:14 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.002111734042548 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 1.7936789e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.7936789e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.7935602e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.002551016543664 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.7935602e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.7935752200000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.7935752200000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 2.69053752e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.0026140013836472003 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.79378702e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0009238003153000002 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0005021970464 | 5 | 30 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 1.7935616200000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0021027173015712 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0021027173015712 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007131927552000001 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.004662256507396 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.000439432 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.0045998228439072 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 6.27744243e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0030624829182544 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0021028336660543997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0249872504458032 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0003946208772 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0012537833383328 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0041874713781824 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.7936315600000004e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.7936315600000004e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0004298927515904001 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0021026863757696 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-05-14 11:26 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0017380788110519998 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 1.4763011000000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.4763011000000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.4763e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0020997710159999998 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.4763e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.4763652200000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.4766232800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 2.2149349200000002e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.0021519680457159998 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.4766613e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0007604805695 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0004134523512 | 5 | 29 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 1.4766613e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0017310659298528 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0017310927525343999 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0058716862902144 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.0038387932931687996 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.0003617764129 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.0037870459574688 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 5.16768609e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0025208268043368 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0017309090734368 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0205703939728944 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0003248659524 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0010322467971168 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0034470533294736 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.4764822200000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.4764822200000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00035388337832960006 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0017309090734368 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-05-15 06:25 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0017983563 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 1.5275000000000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.52743728e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.5275834e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.002173133997136 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.5278798e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.5278798e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.5278798e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 2.2918197000000002e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.002226609790136 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.5278798e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0007868942500000002 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.00042783138719999997 | 5 | 30 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 1.5283014e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.001791656656 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.001791656656 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0060769303296 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.0039729778192 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.0003744286 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.003919488019200001 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 5.34898e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0026088358722824 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0017913399185824 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0212859443621424 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.00033622160000000003 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0010683288512 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0035679836191999997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.5281400000000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.5281400000000002e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0003662273537216 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0017912869297184 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-05-15 18:47 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0018448772173247998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0219224251406448 | 5 | 28 | 14000320 | 13930320 | 99.5 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0003462184 | 23 | 23 | 230000 | 220000 | 95.65 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0011000932288 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0036740696607999996 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.5737200000000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.5737200000000002e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00037716180458880003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0018447302787359997 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0018448168428448 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0018448168428448 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0062580431962752005 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00519928 | 0.0040911054608 | 5 | 30 | 2644640 | 2599640 | 98.3 | 
| Repay | 0.00049 | 0.0003855614 | 5 | 27 | 290000 | 245000 | 84.48 | 
| Flashloan | 0.00512928 | 0.0040360254146784005 | 5 | 28 | 2634640 | 2564640 | 97.34 | 
| Withdraw | 7e-05 | 5.5080199999999995e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00341464 | 0.0026868436304 | 5 | 57 | 1752320 | 1707320 | 97.43 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0018527720304 | 4 | 2 | 1372320 | 1177320 | 85.79 | 
| Swap DAI -> USDC | 2e-05 | 1.5737200000000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.5737200000000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.5737200600000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0022383335157392 | 5 | 30 | 1492320 | 1422320 | 95.31 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.5737200600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.5737200600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.5737200600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 2.36055009e-05 | 4 | 2 | 120000 | 15000 | 12.5 | 
| Add liquidity in metapool | 0.00291464 | 0.0022933845714392 | 4 | 31 | 1462320 | 1457320 | 99.66 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.57370006e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0008104555309 | 5 | 53 | 560000 | 515000 | 91.96 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0004405902032 | 5 | 30 | 330000 | 280000 | 84.85 | 
| Remove liquidity in Metapool | 2e-05 | 1.5735364400000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-17 11:07 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0021468399563039997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.025125674891904 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.4938241e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.001280134266288 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.004275367165608 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.8312747e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.8312747e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.000438919920096 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0021468399563039997 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0021468392294656 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0021467205203424 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007281329107622401 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0043573611836400005 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 0.0001007201228 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0043119932718144 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.40946145e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0022657728610944003 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0021468184794016 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.8312563800000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.8312563800000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.8314000000000005e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.00218325834432 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.8311010000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.8312749600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.83115652e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.83115652e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0021833249234688 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.83115684e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.00011902517379999999 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.1557826e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.8311225200000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-17 13:16 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0022407724479999998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.0262268246932992 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.73459576e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0013362164978879998 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0044626685623519995 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.9115000000000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.9115000000000002e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.000458124352 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0022408896799999997 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.002240891790176 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0022408896799999997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007601133312 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.004548919824 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 0.00010514521490000001 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.004501203194582399 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.6899e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.002365260912 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0022410069119999996 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.9116e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.9115103e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.9115103e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.002279131960896 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.9114e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.9114e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.91133008e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.9114e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0022790004479999997 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.9115000000000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.0001242475 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.557000000000001e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.9114e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-17 15:47 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.00235538314048 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.02756637301248 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 6.033000000000001e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.00140576944 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.00469496104 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.0133909000000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 2.0133909000000002e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00048255681828480003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0023602762400351997 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0023610895956512 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0023638543247999997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.008027976153984002 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.004806325958728 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 0.000111087361 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.004756131920328 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 7.07195314e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0025009865517168 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0023694870644896 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 2.0213382000000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 2.02181102e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 2.02181102e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.002412561988224 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.01674022e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.0163260800000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.0171566400000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 2.0171566400000002e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.002403902883456 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.0151692e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.000130985998 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 0.000100732588 | 5 | 9 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 2.0140258400000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-21 14:24 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.00225144056 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.0263498866338816 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.76150264e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.00134250632 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.00448367612 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.9205000000000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.9205000000000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00046030544 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.00225144056 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.00225144056 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.00225144056 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007636522560000001 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.004570098620000001 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 0.0001056275 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.00452208612 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.72175e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.00237627306 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.002251323328 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.9175726800000004e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.9191340600000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.9191340600000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0022886458398720002 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.9194896000000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.91892032e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.91892032e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.9189000000000002e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.002287942848 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.9189000000000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.00012472849999999998 | 5 | 9 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.5945e-05 | 5 | 9 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.918903e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-22 09:54 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0021267051727328 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.024890032237593597 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.44229994e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0012681284500192 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0042352703773071996 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.81409998e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.81409998e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0004347932392832 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0021266555835968 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0021266555835968 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0021266555835968 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0072132720845568005 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0043170776382712005 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 9.97770334e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0042716180713632 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.34938143e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0022446333231336004 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0021267162394336 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.81410898e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.81410898e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.81410898e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0021629984190336 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.81410898e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.81410898e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.81410898e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.81410898e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0021630209538816 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.81418708e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.00011792216019999998 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.0706394e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.81419954e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-24 09:30 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.001939486208 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.022696164320256 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 4.962602400000001e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0011564428432 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0038622649912 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.65423144e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.65423144e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0003964861915392 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0019393143458879998 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0019393143458879998 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.001939289961632 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.006577758172032 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.003936503764376001 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 9.0983387e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0038951263463376 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 5.78982677e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0020468188668312003 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0019392965969631999 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.65423522e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.6542520600000004e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.6542520600000004e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0019723704166656002 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.6542518600000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.6543000000000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.6544000000000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.6544000000000003e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0019723704166656002 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.6542506800000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.000107536 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 8.272000000000001e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.6544000000000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-28 09:15 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0018183433015872 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.021282960384000002 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 4.6536e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0010842546461152 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0036211722748432 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.5510623800000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.55119994e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0003717586312384 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0018183414493216 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0018183414493216 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0018183414493216 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.006166771860364801 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00477928 | 0.0037060308799096004 | 5 | 10 | 2644640 | 2389640 | 90.36 | 
| Repay | 0.00011 | 8.529807770000001e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0036517502850096 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 0.00011 | 8.529807770000001e-05 | 5 | 9 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00251464 | 0.0019503396207207998 | 5 | 13 | 1752320 | 1257320 | 71.75 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0018184886458207999 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.55073024e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.55073024e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.55087414e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0018491382546048 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.55087414e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.55087414e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.55087414e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.55087414e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0018491382546048 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.5505794800000003e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 0.000116277576 | 5 | 10 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00012 | 9.30203808e-05 | 5 | 9 | 330000 | 60000 | 18.18 | 
| Remove liquidity in Metapool | 2e-05 | 1.5500319e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-05-31 07:41 UTC, anton-lisanin commented
Superseded by https://github.com/neonlabsorg/neon-evm/pull/448

2024-05-31 07:41 UTC, closed without merging