NDEV-3095: Compare status between emulation and receipt
neonlabsorg/neon-evm pull request #460
Opened 2024-06-12 08:25 UTC by andreisilviudragnea

2024-06-24 09:36 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014294850154976 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0167361635670376 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.65809254e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008523843363872001 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028467763891952 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2193641800000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2193641800000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00029225720666240006 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014294850154976 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-06-26 08:25 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-07-03 08:21 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-03 09:21 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-07-05 07:37 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-07-05 07:37 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   79138 |      0     |      0.167 |    0.000678195 |        0      |
| getAccountInfo                    |   54514 |      0     |      0.183 |    0.00133136  |        0      |
| getBlocks                         |   30491 |      0     |      0.037 |    0.0004501   |        0      |
| getTransaction                    |   25126 |      0     |      0.184 |    0.00382926  |        0.001  |
| sendTransaction                   |   23039 |      0     |      0.137 |    0.00332098  |        0.002  |
| getBlock                          |   15303 |      0     |      0.052 |    0.000818467 |        0.001  |
| getMultipleAccounts               |    9190 |      0     |      0.164 |    0.00210326  |        0.001  |
| getBlockTime                      |    5809 |      0     |      0.102 |    0.000614908 |        0      |
| getLatestBlockhash                |    4485 |      0     |      0.139 |    0.00210992  |        0.001  |
| getBalance                        |    1764 |      0     |      0.026 |    0.00127551  |        0      |
| getSignatureStatuses              |    1025 |      0     |      0.036 |    0.00105756  |        0      |
| getVersion                        |     534 |      0     |      0.024 |    0.00111236  |        0      |
| isBlockhashValid                  |     494 |      0     |      0.014 |    0.000384615 |        0      |
| getSignaturesForAddress           |     138 |      0     |      0.006 |    0.00154348  |        0.001  |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.0008125   |        0.001  |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000304348 |        0      |
| getHealth                         |       3 |      0     |      0.015 |    0.00533333  |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

2024-07-05 10:23 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-07-05 10:23 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   72813 |      0     |      0.139 |    0.00134899  |         0.001 |
| getAccountInfo                    |   54719 |      0     |      0.171 |    0.0027402   |         0.001 |
| getBlocks                         |   28202 |      0     |      0.102 |    0.000812035 |         0.001 |
| getTransaction                    |   22468 |      0     |      0.176 |    0.00583149  |         0.002 |
| sendTransaction                   |   20355 |      0     |      0.148 |    0.00593363  |         0.003 |
| getBlock                          |   14166 |      0     |      0.134 |    0.00153875  |         0.001 |
| getMultipleAccounts               |    9320 |      0     |      0.175 |    0.00359936  |         0.001 |
| getBlockTime                      |    5920 |      0     |      0.175 |    0.00140118  |         0.001 |
| getLatestBlockhash                |    4502 |      0     |      0.146 |    0.00316304  |         0.001 |
| getBalance                        |    1769 |      0     |      0.06  |    0.00254664  |         0.001 |
| getSignatureStatuses              |    1038 |      0     |      0.108 |    0.00238054  |         0.001 |
| getVersion                        |     540 |      0     |      0.038 |    0.00256481  |         0.001 |
| isBlockhashValid                  |     501 |      0     |      0.027 |    0.00127944  |         0.001 |
| getSignaturesForAddress           |     130 |      0.001 |      0.008 |    0.00284615  |         0.002 |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00103125  |         0.001 |
| simulateTransaction               |      23 |      0     |      0.002 |    0.000695652 |         0.001 |
| getHealth                         |       4 |      0     |      0.002 |    0.001       |         0.001 |
| getTokenAccountBalance            |       3 |      0.001 |      0.001 |    0.001       |         0.001 |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |         0.001 |

</details>

2024-07-05 10:55 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-07-05 10:56 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   72257 |      0     |      0.086 |    0.000657666 |         0     |
| getAccountInfo                    |   53890 |      0     |      0.113 |    0.00129839  |         0     |
| getBlocks                         |   27823 |      0     |      0.04  |    0.000462531 |         0     |
| getTransaction                    |   25052 |      0     |      0.115 |    0.00325455  |         0.001 |
| sendTransaction                   |   23011 |      0     |      0.101 |    0.00305619  |         0.002 |
| getBlock                          |   13967 |      0     |      0.036 |    0.000827164 |         0.001 |
| getMultipleAccounts               |    8890 |      0     |      0.086 |    0.00182835  |         0.001 |
| getBlockTime                      |    5713 |      0     |      0.08  |    0.000566252 |         0     |
| getLatestBlockhash                |    4439 |      0     |      0.092 |    0.00151904  |         0.001 |
| getBalance                        |    1749 |      0     |      0.085 |    0.00146083  |         0     |
| getSignatureStatuses              |    1024 |      0     |      0.03  |    0.000938477 |         0     |
| getVersion                        |     533 |      0     |      0.021 |    0.000868668 |         0     |
| isBlockhashValid                  |     494 |      0     |      0.015 |    0.00045749  |         0     |
| getSignaturesForAddress           |     135 |      0     |      0.007 |    0.00158519  |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.000625    |         0.001 |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000434783 |         0     |
| getHealth                         |       3 |      0     |      0.002 |    0.000666667 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.002 |      0.002 |    0.002       |         0.002 |

</details>

2024-07-05 12:01 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0165340637201656 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 3.6139187400000005e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0008420912520032 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0028123997490511997 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.2046395800000001e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.2046395800000001e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00028872801453440003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0014122230724256 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0014122230724256 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0048020788505456 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0028666085301512004 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 6.62551769e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0028425157385512 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 6.62551769e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0015025710409256 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0014182462703256 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.2046395800000001e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.8069593700000003e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0014423390619256 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.2046395800000001e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 9.03479685e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 6.62551769e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 1.2046395800000001e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

2024-07-10 13:51 UTC, s-medvedev requested changes

2024-07-10 13:51 UTC, s-medvedev commented on evm_loader/program/src/evm/database.rs
> +    fn logs(&self) -> Vec<Log>;
I wouldn't say I like the idea of using conditional compilation widely. Why you cannot add your own `Log` structure (and don't use it from `web3::types::Log`) and special method `fn log(&self, log: Log)` into `Database`/`Backend` and then implement it different ways for NeonEVM program and emulation logic?
`ExecutorState` and `SyncedExecutorState`, in this case, should just pass it to the backend logc.

2024-07-11 09:40 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-11 09:40 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   74066 |      0     |      0.133 |    0.0010743   |        0.001  |
| getAccountInfo                    |   54798 |      0     |      0.139 |    0.00195662  |        0.001  |
| getBlocks                         |   28374 |      0     |      0.056 |    0.000641749 |        0.001  |
| getTransaction                    |   22589 |      0     |      0.156 |    0.00496126  |        0.001  |
| sendTransaction                   |   20503 |      0     |      0.113 |    0.00515554  |        0.003  |
| getBlock                          |   14242 |      0     |      0.035 |    0.00117694  |        0.001  |
| getMultipleAccounts               |    9350 |      0     |      0.132 |    0.00285947  |        0.001  |
| getBlockTime                      |    5928 |      0     |      0.067 |    0.000913968 |        0      |
| getLatestBlockhash                |    4499 |      0     |      0.208 |    0.0027335   |        0.001  |
| getBalance                        |    1767 |      0     |      0.089 |    0.00183814  |        0.001  |
| getSignatureStatuses              |    1050 |      0     |      0.112 |    0.00188667  |        0.001  |
| getVersion                        |     546 |      0     |      0.045 |    0.00167033  |        0.001  |
| isBlockhashValid                  |     507 |      0     |      0.02  |    0.000723866 |        0      |
| getSignaturesForAddress           |     139 |      0     |      0.007 |    0.00205036  |        0.002  |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.001       |        0.001  |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000782609 |        0.001  |
| getHealth                         |       3 |      0.001 |      0.001 |    0.001       |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |
| getClusterNodes                   |       1 |      0.024 |      0.024 |    0.024       |        0.024  |

</details>

2024-07-11 09:56 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-11 09:56 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   81033 |          0 |      0.326 |    0.000497254 |        0      |
| getAccountInfo                    |   54425 |          0 |      0.082 |    0.000944162 |        0      |
| getBlocks                         |   30395 |          0 |      0.031 |    0.000302846 |        0      |
| getTransaction                    |   26657 |          0 |      0.087 |    0.00263428  |        0.001  |
| sendTransaction                   |   24556 |          0 |      0.071 |    0.00278535  |        0.001  |
| getBlock                          |   15249 |          0 |      0.035 |    0.000606728 |        0.001  |
| getMultipleAccounts               |    9028 |          0 |      0.074 |    0.00153556  |        0.001  |
| getBlockTime                      |    5733 |          0 |      0.045 |    0.000385836 |        0      |
| getLatestBlockhash                |    4487 |          0 |      0.069 |    0.00156385  |        0      |
| getBalance                        |    1767 |          0 |      0.018 |    0.000721562 |        0      |
| getSignatureStatuses              |    1020 |          0 |      0.039 |    0.000714706 |        0      |
| getVersion                        |     531 |          0 |      0.031 |    0.000723164 |        0      |
| isBlockhashValid                  |     492 |          0 |      0.011 |    0.000280488 |        0      |
| getSignaturesForAddress           |     133 |          0 |      0.01  |    0.00121053  |        0.001  |
| requestAirdrop                    |      32 |          0 |      0.001 |    0.0004375   |        0      |
| simulateTransaction               |      23 |          0 |      0.001 |    0.000347826 |        0      |
| getHealth                         |       3 |          0 |      0.001 |    0.000666667 |        0.001  |
| getTokenAccountBalance            |       3 |          0 |      0     |    0           |        0      |
| getFirstAvailableBlock            |       2 |          0 |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |          0 |      0     |    0           |        0      |
| getClusterNodes                   |       1 |          0 |      0     |    0           |        0      |

</details>

2024-07-11 10:10 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-11 10:10 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   74271 |      0     |      0.149 |    0.00105532  |         0.001 |
| getAccountInfo                    |   54188 |      0     |      0.231 |    0.00198791  |         0.001 |
| getBlocks                         |   27922 |      0     |      0.154 |    0.000623666 |         0.001 |
| getTransaction                    |   24718 |      0     |      0.213 |    0.00472736  |         0.001 |
| sendTransaction                   |   22682 |      0     |      0.149 |    0.00468971  |         0.003 |
| getBlock                          |   14019 |      0     |      0.044 |    0.00124053  |         0.001 |
| getMultipleAccounts               |    9094 |      0     |      0.115 |    0.00282142  |         0.001 |
| getBlockTime                      |    5806 |      0     |      0.211 |    0.000934034 |         0     |
| getLatestBlockhash                |    4459 |      0     |      0.149 |    0.00251738  |         0.001 |
| getBalance                        |    1755 |      0     |      0.045 |    0.00185698  |         0.001 |
| getSignatureStatuses              |    1031 |      0     |      0.043 |    0.0016935   |         0.001 |
| getVersion                        |     537 |      0     |      0.044 |    0.00159963  |         0.001 |
| isBlockhashValid                  |     497 |      0     |      0.023 |    0.000911469 |         0     |
| getSignaturesForAddress           |     134 |      0     |      0.006 |    0.00211194  |         0.002 |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00096875  |         0.001 |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000434783 |         0     |
| getHealth                         |       4 |      0     |      0.001 |    0.00025     |         0     |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000666667 |         0.001 |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |         0.001 |

</details>

2024-07-11 10:31 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-11 11:15 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-11 11:16 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   81164 |      0     |      0.084 |    0.000414642 |        0      |
| getAccountInfo                    |   54349 |      0     |      0.08  |    0.000940624 |        0      |
| getBlocks                         |   30072 |      0     |      0.035 |    0.000271249 |        0      |
| getTransaction                    |   29459 |      0     |      0.314 |    0.00257853  |        0.001  |
| sendTransaction                   |   27371 |      0     |      0.096 |    0.00254284  |        0.001  |
| getBlock                          |   15090 |      0     |      0.019 |    0.000534592 |        0      |
| getMultipleAccounts               |    8925 |      0     |      0.086 |    0.00139552  |        0.001  |
| getBlockTime                      |    5694 |      0     |      0.04  |    0.000422374 |        0      |
| getLatestBlockhash                |    4481 |      0     |      0.071 |    0.00132292  |        0      |
| getBalance                        |    1766 |      0     |      0.013 |    0.000896942 |        0      |
| getSignatureStatuses              |    1022 |      0     |      0.06  |    0.000722114 |        0      |
| getVersion                        |     532 |      0     |      0.04  |    0.000768797 |        0      |
| isBlockhashValid                  |     493 |      0     |      0.012 |    0.000239351 |        0      |
| getSignaturesForAddress           |     136 |      0     |      0.003 |    0.00108824  |        0.001  |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.000375    |        0      |
| simulateTransaction               |      23 |      0     |      0.001 |    0.00026087  |        0      |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0     |      0     |    0           |        0      |

</details>

2024-07-11 17:12 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-12 09:00 UTC, neonlabstech commented
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

2024-07-12 09:01 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   73758 |      0     |      0.144 |    0.000867852 |        0      |
| getAccountInfo                    |   55086 |      0     |      0.147 |    0.00174019  |        0.001  |
| getBlocks                         |   27411 |      0     |      0.032 |    0.000542519 |        0      |
| getTransaction                    |   24562 |      0     |      0.157 |    0.00418337  |        0.001  |
| sendTransaction                   |   22432 |      0     |      0.144 |    0.0040802   |        0.002  |
| getBlock                          |   13764 |      0     |      0.045 |    0.000972537 |        0.001  |
| getMultipleAccounts               |    9223 |      0     |      0.115 |    0.00244476  |        0.001  |
| getBlockTime                      |    5882 |      0     |      0.098 |    0.000849371 |        0      |
| getLatestBlockhash                |    4530 |      0     |      0.118 |    0.00234393  |        0.001  |
| getBalance                        |    1780 |      0     |      0.043 |    0.00162978  |        0.001  |
| getSignatureStatuses              |    1040 |      0     |      0.036 |    0.00141154  |        0.001  |
| getVersion                        |     542 |      0     |      0.05  |    0.00145018  |        0      |
| isBlockhashValid                  |     501 |      0     |      0.025 |    0.000736527 |        0      |
| getSignaturesForAddress           |     143 |      0     |      0.007 |    0.00237762  |        0.002  |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0009375   |        0.001  |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000652174 |        0.001  |
| getHealth                         |       4 |      0     |      0.001 |    0.0005      |        0.0005 |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |        0.001  |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

2024-07-15 05:54 UTC, s-medvedev approved these changes

2024-07-15 08:45 UTC, merged