Accounts whitelists #468
neonlabsorg/neon-evm pull request #487
Opened 2022-01-25 14:33 UTC by ivandzen

2022-01-25 15:22 UTC, vasiliy-zaznobin requested changes
you need to add public keys for devnet/testnet/mainnet and add a step in the mainnet launch scenario

2022-01-26 13:41 UTC, vasiliy-zaznobin approved these changes

2022-01-27 04:24 UTC, s-medvedev reviewed
What about `account_whitelists` for devnet/testnet environment? Should we specify tokens for them too? Or we need to explicitly specify in config.rs that we do not place tokens there (but in this case, we get a configuration there that is different from CI/mainnet)

2022-01-27 12:06 UTC, s-medvedev approved these changes

2022-01-27 12:07 UTC, merged