Added Allure report to summary
neonlabsorg/neon-evm pull request #595
Opened 2024-12-24 17:42 UTC by IvanAdamovNeon

2024-12-24 19:18 UTC, neonlabstech commented
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/12485232999/artifacts/2360036606)

2024-12-24 19:18 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   63334 |      0     |      0.255 |    0.000718666 |        0      |
| getSlot                           |   58129 |      0     |      0.137 |    0.000549485 |        0      |
| getBlocks                         |   27465 |      0     |      0.065 |    0.000478755 |        0      |
| getMultipleAccounts               |   15383 |      0     |      0.243 |    0.00169167  |        0.001  |
| getBlock                          |   13924 |      0     |      0.05  |    0.00130487  |        0.001  |
| getTransaction                    |   10358 |      0     |      0.257 |    0.0114252   |        0.003  |
| getLatestBlockhash                |   10289 |      0     |      0.254 |    0.00167635  |        0      |
| getBlockTime                      |    6282 |      0     |      0.051 |    0.000400669 |        0      |
| sendTransaction                   |    5254 |      0     |      0.256 |    0.00925333  |        0.005  |
| getBalance                        |    1802 |      0     |      0.141 |    0.00100832  |        0      |
| getSignatureStatuses              |    1165 |      0     |      0.068 |    0.00092618  |        0.001  |
| getVersion                        |     623 |      0     |      0.06  |    0.00134992  |        0      |
| isBlockhashValid                  |     564 |      0     |      0.005 |    0.000351064 |        0      |
| simulateTransaction               |     560 |      0     |      0.003 |    0.0008625   |        0.001  |
| getSignaturesForAddress           |      67 |      0     |      0.004 |    0.00173134  |        0.002  |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00071875  |        0.001  |
| getTokenAccountBalance            |      12 |      0     |      0.067 |    0.00841667  |        0.001  |
| getHealth                         |       3 |      0     |      0.012 |    0.00433333  |        0.001  |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

2024-12-24 21:06 UTC, neonlabstech commented
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/12486052806/artifacts/2360187513)

2024-12-28 00:55 UTC, neonlabstech commented
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/12522227068/artifacts/2367096426)

2024-12-28 02:05 UTC, neonlabstech commented
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/12522623495/artifacts/2367180504)

2025-01-08 13:44 UTC, kristinaNikolaevaa requested changes

2025-01-08 13:44 UTC, kristinaNikolaevaa commented on .github/workflows/pipeline.yml
> +      - name: Get neon-core-api logs
lets delete it 
we don't need this step anymore

2025-01-08 13:44 UTC, kristinaNikolaevaa commented on .github/workflows/pipeline.yml
> -          python3 ./.github/workflows/deploy.py run_tests \
also let's delete run_tests function from script as you rewrited it

2025-01-08 18:07 UTC, neonlabstech commented
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/12676132793/artifacts/2403063380)

2025-01-08 19:02 UTC, neonlabstech commented
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/12677087835/artifacts/2403346853)

2025-01-08 19:55 UTC, neonlabstech commented
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/12677630365/artifacts/2403590883)

2025-01-08 19:55 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   65709 |      0     |      0.132 |    0.000387907 |         0     |
| getAccountInfo                    |   62439 |      0     |      0.159 |    0.000492048 |         0     |
| getBlocks                         |   28009 |      0     |      0.053 |    0.000381449 |         0     |
| getMultipleAccounts               |   15436 |      0     |      0.111 |    0.00112341  |         0.001 |
| getBlock                          |   14155 |      0     |      0.015 |    0.000718262 |         0.001 |
| getLatestBlockhash                |   10396 |      0     |      0.129 |    0.0011313   |         0     |
| getTransaction                    |   10212 |      0     |      0.171 |    0.0074763   |         0.002 |
| getBlockTime                      |    6256 |      0     |      0.1   |    0.000307864 |         0     |
| sendTransaction                   |    5182 |      0     |      0.113 |    0.00630355  |         0.003 |
| getBalance                        |    1789 |      0     |      0.113 |    0.000613192 |         0     |
| getSignatureStatuses              |    1130 |      0     |      0.139 |    0.000706195 |         0     |
| simulateTransaction               |     560 |      0     |      0.002 |    0.000771429 |         0.001 |
| isBlockhashValid                  |     547 |      0     |      0.005 |    0.000288848 |         0     |
| getVersion                        |     541 |      0     |      0.05  |    0.000914972 |         0     |
| getSignaturesForAddress           |      61 |      0     |      0.011 |    0.00154098  |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0005625   |         0.001 |
| getBlockHeight                    |      13 |      0     |      0.001 |    0.000230769 |         0     |
| getTokenAccountBalance            |      12 |      0     |      0.055 |    0.00916667  |         0     |
| getHealth                         |       3 |      0     |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |      0     |      0     |    0           |         0     |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |         0.001 |

</details>

2025-01-09 09:40 UTC, kristinaNikolaevaa approved these changes

2025-01-09 17:05 UTC, merged