Use sol_log_data to store Neon events
neonlabsorg/neon-evm pull request #677
Opened 2022-05-17 13:24 UTC by vakond

2022-05-17 13:35 UTC, anton-lisanin requested changes

2022-06-24 06:42 UTC, otselnik approved these changes
Everything is OK for me. Should be merged after proxy.

2022-07-19 15:13 UTC, otselnik approved these changes

2022-07-21 06:29 UTC, anton-lisanin approved these changes

2022-07-21 17:02 UTC, merged