alt_cost impl
neonlabsorg/neon-evm pull request #748
Opened 2022-09-14 21:40 UTC by valiksinev

2022-09-15 14:51 UTC, anton-lisanin requested changes

2022-09-15 14:51 UTC, anton-lisanin commented on evm_loader/program/src/instruction/transaction.rs
> +    finalize(accounts, storage, account_storage, results, used_gas + alt_cost)
`used_gas + alt_cost` can overflow

2022-09-16 07:01 UTC, valiksinev commented on evm_loader/program/src/instruction/transaction.rs
> +    finalize(accounts, storage, account_storage, results, used_gas + alt_cost)
fixed

2022-09-20 22:26 UTC, afalaleev approved these changes

2022-09-20 22:27 UTC, merged