added neon-cli tests
neonlabsorg/neon-evm pull request #820
Opened 2022-11-17 14:19 UTC by kristinaNikolaevaa

2022-11-18 08:08 UTC, gigimon requested changes

2022-11-18 08:08 UTC, gigimon commented on evm_loader/tests/test_cli.py
> +    assert len(result) > 1000
I think here we need add more logic to checks. Check addresses, transaction, balances, something that show us success executed command

2022-11-18 08:08 UTC, gigimon commented on evm_loader/tests/test_cli.py
> +    result = neon_cli().call(f"init-environment --evm_loader {evm_loader.loader_id}")
same too

2022-11-18 08:08 UTC, gigimon commented on evm_loader/tests/test_cli.py
> +        f"get-ether-account-data --evm_loader {evm_loader.loader_id} {user_account.eth_address.hex()}")
here we need to check result (account data)

2022-11-18 08:08 UTC, gigimon commented on evm_loader/tests/test_cli.py
> +        f"deposit --evm_loader {evm_loader.loader_id} 10 {user_account.eth_address.hex()}").strip()
maybe here we can check balance before/after?

2022-11-18 12:25 UTC, gigimon approved these changes

2022-11-18 12:25 UTC, gigimon commented on evm_loader/tests/test_cli.py
> +    assert f"{index}: collect {amount} lamports from {treasury_pool_address}" in result
wait new amount in main pool address

2022-11-21 08:36 UTC, gigimon approved these changes

2022-11-21 09:15 UTC, anton-lisanin commented on evm_loader/tests/test_cli.py
> +def test_cancel_trx(evm_loader, user_account, deployed_contract, operator_keypair, treasury_pool):
This test should pass now

2022-11-23 07:07 UTC, anton-lisanin approved these changes

2022-11-23 09:49 UTC, merged